NMS-12874: Renamed RemotePoller to PerspectivePoller
OpenNMS/opennms pull request #3135
Opened 2020-08-28 13:02 UTC by fooker

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12874

2020-08-28 13:02 UTC, fooker commented
Waiting for #3133 to be merged first...

2020-08-31 06:31 UTC, christianpape requested changes
Just a few comments

2020-08-31 06:31 UTC, christianpape commented on features/perspectivepoller/src/test/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerdIT.java
> +        "classpath:/META-INF/opennms/applicationContext-testPerpsectivePollerDaemon.xml",
Typo

2020-08-31 06:31 UTC, christianpape commented on features/perspectivepoller/src/test/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerdIT.java
> +        assertThat(findperspectivePolledService(this.node1icmp, "RDU").getPkg().getName(), is("foo1"));
upper case P please, findPerspectivePolledService

2020-09-02 13:41 UTC, merged