Feature/enhance snmp iface poller
OpenNMS/opennms pull request #3178
Opened 2020-10-06 23:01 UTC by dschlenk

### All Contributors

* [X] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

2020-10-06 23:02 UTC, dschlenk commented
clearly this is a WIP, just hopping in with a PR to get tests to run

2020-10-30 22:41 UTC, dschlenk commented
alright I've done some manual testing and found some issues that are now corrected. I also [documented my testing](https://gist.github.com/dschlenk/06f5c29b11bef756ecbb5afa0499cd87).

2020-11-03 07:52 UTC, christianpape commented on opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
> +            &lt;/p> &lt;p>The notPresent state indicates that the interface is down specifically because
Maybe "The not present state" like in the other definitions.

2020-11-03 08:11 UTC, christianpape commented on opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpinterfacepoller/Package.java
> -            return Objects.equals(this.m_name, this.m_name)
Good catch!

2020-11-03 08:16 UTC, christianpape commented on opennms-config/src/test/java/org/opennms/netmgt/config/SnmpInterfacePollerConfigFactoryTest.java
> + * Copyright (C) 2006-2014 The OpenNMS Group, Inc.
Copyright (C) 2020 The OpenNMS Group, Inc.

2020-11-03 08:18 UTC, christianpape commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
> +Another use of this policy is to mark interfaces for polling by the SNMP Interface Poller. The SNMP Interface Poller is a separate daemon that is disabled by default. In order for a this daemon to do
"In order for a this daemon" -> "In order for this daemon"

2020-11-03 08:20 UTC, christianpape commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
> +Decide to move all your meetings to Minecraft and Mumble? Decommission your voice circuits and flip the the action to _DISABLE_POLLING_!
What?

2020-11-03 08:21 UTC, christianpape commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
> +Decide to move all your meetings to Minecraft and Mumble? Decommission your voice circuits and flip the the action to _DISABLE_POLLING_!
"the the" -> "the"

2020-11-03 08:22 UTC, christianpape commented on opennms-doc/guide-admin/src/asciidoc/text/snmp-poller/concepts.adoc
> +On a configurable time interval an SNMP GET request is made for two specific objects in an `ifEntry` of the `ifTable` defined in the `IF-MIB`:
a SNMP GET

2020-11-03 08:33 UTC, christianpape commented on opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/pollable/PollableSnmpInterface.java
> +import org.opennms.netmgt.snmpinterfacepoller.pollable.SnmpInterfaceStatus.*;
No .* imports, please.

2020-11-03 08:35 UTC, christianpape commented on opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/pollable/PollableSnmpInterface.java
> +            if (adminstatus.getMibValue() > 3 )
Please use { ... } for blocks, even for one-line blocks.

2020-11-03 08:40 UTC, christianpape requested changes
Looks good. Only some small changes needed.

2020-11-03 14:53 UTC, christianpape approved these changes
Looks good to me.

2020-11-20 15:21 UTC, merged

2020-11-25 19:11 UTC, Bonrob2 commented
@dschlenk going forward, for documentation changes, please add me to the review. Thanks!

2020-11-25 19:14 UTC, dschlenk commented
@Bonrob2 will do! I wrote most of it while stuck in a winnebago in northern MN, was it that obvious?

2020-11-25 19:23 UTC, Bonrob2 commented
@dschlenk LOL. Not at all, minor tweaks ... it just helps us as we migrate the docs to see what's happening. :-)