NMS-12949: Persist BMP messages
OpenNMS/opennms pull request #3193
Opened 2020-10-21 13:49 UTC by cgorantla

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12949

2020-11-19 14:16 UTC, fooker requested changes
Looks good.
On question: How do we configure the persistence RRAs and does this resonate with the stats update strategy?

2020-11-19 14:16 UTC, fooker commented on features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpMessagePersister.java
> +                            Integer count = state ? ++connections : --connections;
Lovin' it

2020-12-01 00:20 UTC, cgorantla reviewed
> Looks good.
> On question: How do we configure the persistence RRAs and does this resonate with the stats update strategy?

Updated RRAs in config. Currently stats get updated like all other telemetry metrics.

2020-12-01 09:08 UTC, fooker requested changes
I like it a lot. Especially the `State` handling. Just a few minor nits left.

2020-12-01 09:08 UTC, fooker commented on core/schema/src/main/liquibase/27.0.0/changelog.xml
> +        <column name="state" type="varchar(8)">
Do we need a default value here, too?

2020-12-01 09:08 UTC, fooker commented on features/telemetry/protocols/bmp/persistence/impl/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/persistence/impl/BmpGlobalIpRibDaoImpl.java
> +public class    BmpGlobalIpRibDaoImpl extends AbstractDaoHibernate<BmpGlobalIpRib, Long> implements BmpGlobalIpRibDao {
Oops

2020-12-01 22:02 UTC, fooker approved these changes

2020-12-02 13:34 UTC, merged