NMS-12985: Fixed another typo in VmwareAssetsMigratorOffline
OpenNMS/opennms pull request #3207
Opened 2020-11-04 19:05 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-12985

2020-11-04 21:22 UTC, RangerRick approved these changes
guess I missed one  :D

2020-11-05 12:32 UTC, fooker requested changes

2020-11-05 12:32 UTC, fooker commented on core/upgrade/src/test/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOfflineIT.java
> +    public void foo() throws Exception {
```suggestion
    public void bar() throws Exception {
```

2020-11-05 12:32 UTC, fooker commented on core/upgrade/src/test/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOfflineIT.java
> +    TransactionOperations transactionOperations;
Use `SessionUtils` instead.

2020-11-05 12:35 UTC, fooker approved these changes

2020-11-05 12:37 UTC, fooker commented
@RangerRick is this the right target branch or should this go into `release-27.x` instead?

2020-11-05 12:37 UTC, RangerRick commented
Oh yeah definitely 27

2020-11-05 12:40 UTC, opennms-bamboo commented
Welcome CI/CD System (cicd-system@opennms.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username CI/CD System (cicd-system@opennms.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](https://wiki.opennms.org/wiki/images/6/6b/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit https://wiki.opennms.org/wiki/Contributor_Agreement

2020-11-05 12:40 UTC, fooker commented
@christianpape I've updated the target branch, but you have to rebase.

2020-11-05 14:57 UTC, RangerRick approved these changes
yay, tests

2020-11-05 14:58 UTC, merged