NMS-13061: Update stat aggregations
OpenNMS/opennms pull request #3262
Opened 2021-01-13 14:26 UTC by cgorantla

Support timescaledb in Postgres.
Add stat aggregations for BMP

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13061

2021-01-13 15:21 UTC, opennms-bamboo commented
Welcome CI/CD System (cicd-system@opennms.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username CI/CD System (cicd-system@opennms.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](https://wiki.opennms.org/wiki/images/6/6b/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit https://wiki.opennms.org/wiki/Contributor_Agreement

2021-01-15 09:29 UTC, christianpape requested changes
Only some small things...

2021-01-15 09:29 UTC, christianpape commented on core/schema/src/main/liquibase/28.0.0/changelog.xml
> +  <changeSet author="cgorantla" id="27.0.0-bmp-ip-rib-log">
27.0.0 for the id? This is the 28.0.0 changelog, so I think it should contain only id starting with 28.

2021-01-15 09:29 UTC, christianpape commented on features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpMessagePersister.java
> +                LOG.error("Exception while persisting BMP Stats by Asn  {}", stat, e);
two space before {}

2021-01-15 09:29 UTC, christianpape commented on features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpMessagePersister.java
> +                LOG.error("Exception while persisting BMP Stats by Prefix  {}", stat, e);
same here

2021-01-15 09:29 UTC, christianpape commented on features/telemetry/protocols/bmp/persistence/impl/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/persistence/impl/BmpStatsByPrefixDaoImpl.java
> +    public BmpStatsByPrefix findByPrefixAndIntervalTime(String peerHashId, String prefix, Integer prefixLen, Date intervalTime) {        Criteria criteria = new Criteria(BmpStatsByPeer.class);
Missing line break

2021-01-27 14:09 UTC, opennms-bamboo commented
Welcome CI/CD System (cicd-system@opennms.com).

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username CI/CD System (cicd-system@opennms.com).
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](https://wiki.opennms.org/wiki/images/6/6b/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit https://wiki.opennms.org/wiki/Contributor_Agreement

2021-01-27 14:18 UTC, cgorantla commented
@christianpape Can you review it one more time. Moved all the scheduled things to Stats module which runs only on OpenNMS and fixed some issues.

2021-02-01 19:03 UTC, christianpape approved these changes
LGTM

2021-02-06 17:47 UTC, merged