NMS-13118/NMS-13109: Modified handling of meta-data
OpenNMS/opennms pull request #3291
Opened 2021-02-08 11:03 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-13118
* JIRA: https://issues.opennms.org/browse/NMS-13109

2021-02-08 21:12 UTC, cgorantla requested changes

2021-02-09 07:12 UTC, christianpape commented on opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
> +                        final OnmsMonitoredService nodeMonitoredService = nodeInterface.getMonitoredServiceByServiceType(dbNodeMonitoredService.getServiceName());
done.

2021-02-09 11:52 UTC, indigo423 commented
Here is what I've tested:

## NMS-13118
* Added a new node in a requisition and synched it with "Yes"  -> 👍 
* Changed meta-data and added a new attribute and synched with "Yes" and "DB only" -> 👍 

## NMS-13109
* Imported nodes from vCenter with Provisiond schedule and added additional meta-data manually -> 👍 
* Reimported vCenter with Provisiond schedule and check if meta-data is still available -> 👍

2021-02-09 11:52 UTC, indigo423 approved these changes
Here is what I've tested:

## NMS-13118
* Added a new node in a requisition and synched it with "Yes"  -> 👍 
* Changed meta-data and added a new attribute and synched with "Yes" and "DB only" -> 👍 

## NMS-13109
* Imported nodes from vCenter with Provisiond schedule and added additional meta-data manually -> 👍 
* Reimported vCenter with Provisiond schedule and check if meta-data is still available -> 👍

2021-02-09 14:30 UTC, cgorantla commented on opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/MetaDataIT.java
> +        m_nodeDao.update(node);
Can we add metadata for Service as well and verify that it updates properly.

2021-02-09 15:30 UTC, cgorantla approved these changes

2021-02-09 15:55 UTC, merged