NMS-12753: Add encryption option for snmp config (#3054)
OpenNMS/opennms pull request #3295
Opened 2021-02-10 19:57 UTC by cgorantla

* NMS-12753: Add encryption for snmp

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12753

2021-02-10 19:57 UTC, cgorantla commented
Cherry picking this from features/space branch.
Review once again, Need feedback if it is okay to merge this into `foundation-2020`

2021-05-13 16:35 UTC, RangerRick requested changes
just marking as request changes for feedback on the changes to `apt-get` -- this looks suspect to me

2021-09-21 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3295) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3295) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS/opennms?pullRequest=3295) it.</sub>

2021-11-01 16:34 UTC, RangerRick approved these changes

2021-11-01 16:35 UTC, RangerRick commented
@cgorantla looks like this needs some conflict-fixing

2021-11-10 19:54 UTC, mmahacek commented
Docs path in 2021+ has changed

2021-11-24 15:42 UTC, RangerRick approved these changes

2021-11-24 20:15 UTC, mmahacek reviewed
As there will need to be manual merging into 2021 due to the Antora migration for docs, the fewer doc pages modified, the easier that merge will be.

2021-11-24 20:15 UTC, mmahacek commented on opennms-doc/guide-admin/src/asciidoc/index.adoc
> +
```suggestion
```

2021-11-24 21:14 UTC, Bonrob2 reviewed
A few changes in the doc files.

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +==== Encrypting SNMP Credentials
```suggestion
==== Encrypt SNMP credentials
```

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +You can save SNMP credentials like readCommunity/WriteCommunity, authPassPhrase/privPassPhrase on the file system in encrypted format.
```suggestion
You can save SNMP credentials like readCommunity/WriteCommunity or authPassPhrase/privPassPhrase on the file system in encrypted format.
```

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +A random password is generated (once) for `snmp-config` alias and it is stored in java keystore file at `$OPENNMS_HOME/etc/scv.jce`.
```suggestion
A random password is generated (once) for the `snmp-config` alias and it is stored in a Java keystore file at `$OPENNMS_HOME/etc/scv.jce`.
```

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +This password is used to encrypt/decrypt SNMP credentials.
```suggestion
This password encrypts/decrypts SNMP credentials.
```
Does the password do this, or does one require the password so SNMP credentials can be encrypted/decrypted?

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +===== Enabling Encrption on SNMP Config
```suggestion
===== Enable encryption on SNMP config
```

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
> +Enable encryption on SNMP config by setting the following system property:
```suggestion
Set the following system property to enable encryption on SNMP config:
```

2021-11-24 21:14 UTC, Bonrob2 commented on opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
>  Currently in {opennms-product-name}, the ICMP is used to automatically provision node entities into {opennms-product-name}.
```suggestion
Currently {opennms-product-name} uses the ICMP to automatically provision node entities into {opennms-product-name}.
```

2021-12-20 16:04 UTC, cgorantla commented
Closing this for now. Will revisit when we have standard way of doing encryption for all the modules.

2021-12-20 16:04 UTC, closed without merging