NMS-13075: WmiDetector documentation
OpenNMS/opennms pull request #3347
Opened 2021-03-18 17:25 UTC by mfuhrmann

### All Contributors

* [ ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13075

2021-03-18 17:26 UTC, mfuhrmann commented
I've collected information from the Wiki to create this PR. Unfortunately, I don't have a working example to add here.

2021-03-19 09:45 UTC, indigo423 approved these changes
just the copy & paste formatting fix. 👍

2021-03-19 09:45 UTC, indigo423 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +The WMI Detector can be used to detect the availability of WmiConfiguration on a device when scanning it using Provisiond. By default, it expects to make a WMI query to the `Win32_ComputerSystem` cla
one line one sentence

2021-03-19 15:21 UTC, mfuhrmann commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +The WMI Detector can be used to detect the availability of WmiConfiguration on a device when scanning it using Provisiond. By default, it expects to make a WMI query to the `Win32_ComputerSystem` cla
fixed

2021-03-19 20:56 UTC, Bonrob2 requested changes
Just a few changes. Thanks for all the work.

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +The WMI Detector can be used to detect the availability of WmiConfiguration on a device when scanning it using Provisiond. By default, it expects to make a WMI query to the `Win32_ComputerSystem` cla
```suggestion
Use the WMI Detector to detect the availability of WmiConfiguration on a device when scanning it using Provisiond. By default, it expects to make a WMI query to the `Win32_ComputerSystem` class, checking for `OK` from the "Status" object.
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +| `wmiClass`   | This is the class of instances within WMI. An example of this would be the `Win32_ComputerSystem` class. This class contains objects representing properties and methods available.  |
```suggestion
| `wmiClass`   | The class of instances within WMI. An example would be the `Win32_ComputerSystem` class. This class contains objects representing properties and methods available.  | Required | `Win32_ComputerSystem`
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +| `wmiWqlStr`   | Microsoft WMI also implements an `ExecQuery` method which is more common in Windows scripting but less common in OpenNMS polling and monitoring. WQL, which stands for "SQL For WMI"
```suggestion
| `wmiWqlStr`   | Microsoft WMI also implements an `ExecQuery` method which is more common in Windows scripting but less common in OpenNMS polling and monitoring. WQL, which stands for "SQL For WMI" according to Microsoft, is a simple SQL-like syntax for querying WMI classes, properties, and instances. Here's an example of a WQL query that you could use to discover whether a Windows service is running: `Select State From Win32_Service Where Name='Server'` | Required | `NOTSET`
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +| `compOp`   a| The compare operation is how you tell the OpenNMS WMI poller plugins how to verify the nature (up, critical) of a specific property within WMI. In the event of unequal comparisons the
```suggestion
| `compOp`   a| The compare operation is how you tell the OpenNMS WMI poller plugins how to verify the nature (up, critical) of a specific property within WMI. In the event of unequal comparisons, the system will always have the WMI value (as retrieved from the target) on the left. Available compare operations are:
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +The NOOP operation is a special case in which the Manager will always return a result code of "OK." This is typical used in scenarios where the existence of a class or property is more interesting th
```suggestion
The NOOP operation is a special case in which the Manager will always return a result code of "OK". This is typically used in scenarios where the existence of a class or property is more interesting than the contents of the property. We use this in the collector to check and ensure that WMI is available before attempting to collect data. | Required | `EQ`
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +* `one` only one instance can comply with the compare operation. | Required | `all`
```suggestion
* `one` only one instance can comply with the compare operation | Required | `all`
```

2021-03-19 20:56 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc
> +| `wmiObject`   | A WMI Object is technically a member of a WMI property set. Using the previous example of `Win32_ComputerSystem` this class contains a variety of properties that we can look at and
```suggestion
| `wmiObject`   | A WMI object is technically a member of a WMI property set. Using the previous example of `Win32_ComputerSystem` this class contains a variety of properties that we can look at and poll. The default WMI service uses the `Status` property to determine if the system is running and if WMI is available. | Required | `Status`
```

2021-03-29 20:01 UTC, Bonrob2 requested changes
Looks good. Just a few changes.

2021-03-30 07:05 UTC, merged