NMS-13231: Backport Security Issues from Last Month
OpenNMS/opennms pull request #3375
Opened 2021-04-12 08:35 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-13231

2021-04-14 14:18 UTC, fooker requested changes
There are some unused code fragments left over from back-porting.

2021-04-14 14:18 UTC, fooker commented on smoke-test/src/test/java/org/opennms/smoketest/NotificationsPageIT.java
> +
This is unused

2021-04-14 14:18 UTC, fooker commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/ForeignSource.test.js
> +const _ = require('underscore-js');
This is unused

2021-04-14 14:18 UTC, fooker commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Node.test.js
> +const _ = require('underscore-js');
This is unused

2021-04-14 14:18 UTC, fooker commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Requisition.test.js
> +const _ = require('underscore-js');
This is unused

2021-04-14 14:18 UTC, fooker commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Requisitions.test.js
> +const _ = require('underscore-js');
This is unused

2021-04-15 09:00 UTC, christianpape commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/ForeignSource.test.js
> +const _ = require('underscore-js');
Without this entry the tests fail.

2021-04-15 09:03 UTC, christianpape commented on smoke-test/src/test/java/org/opennms/smoketest/NotificationsPageIT.java
> +
Fixed.

2021-04-15 09:03 UTC, christianpape commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Node.test.js
> +const _ = require('underscore-js');
Without this entry the tests fail.

2021-04-15 09:03 UTC, christianpape commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Requisition.test.js
> +const _ = require('underscore-js');
Without this entry the tests fail.

2021-04-15 09:03 UTC, christianpape commented on core/web-assets/src/test/javascript/ng-requisitions/controllers/Requisitions.test.js
> +const _ = require('underscore-js');
Without this entry the tests fail.

2021-04-19 17:20 UTC, RangerRick approved these changes

2021-04-20 08:35 UTC, fooker approved these changes

2021-04-20 12:25 UTC, merged