Jira/NMS-13225 Update help page with Antora, OpenAPI, and Swagger UI links
OpenNMS/opennms pull request #3392
Opened 2021-04-23 14:31 UTC by jadyhou

Update help page with Antora, OpenAPI, and Swagger UI links.

Because we don't have offline doc anymore, the corresponding code is removed here too. 

Adding Bonnie to see if she has suggestions for the wording of the newly added "OpenAPI" and "Swagger UI" description. 

Below is the screenshot of the help page.
 
![image](https://user-images.githubusercontent.com/4617120/115885681-2a43e980-a41e-11eb-8591-c137efeef8e6.png)

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13225

2021-04-23 18:17 UTC, Bonrob2 requested changes
@jadyhou It would be good to update the other text on this screen. It it is an issue to update as part of this PR, let me know and I can create a separate ticket. I'd like to update the content on the rest of this screen too.

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                      <td style="border-top: none;">OpenNMS can be installed several operating systems and can be deployed for several scenarios with different technologies. Have a look in the Installa
```suggestion
                    <td style="border-top: none;">Learn how to deploy and configure the OpenNMS core, Minion, and Sentinel. The guide also covers how to set up a message broker, time series storage options,and setting up Jaeger tracing.</td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                              style="width: 100%">Admin Guide</a></td>
```suggestion
                            style="width: 100%">Operation Guide</a></td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                      <td style="border-top: none;">Have a look into the Admin Guide to find instructions how to configure OpenNMS to monitor your infrastructure and services.</td>
```suggestion
                    <td style="border-top: none;">Learn how to configure OpenNMS to monitor your infrastructure and services.</td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                              style="width: 100%">Developers Guide</a></td>
```suggestion
                            style="width: 100%">Development Guide</a></td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                      <td style="border-top: none;">Developers can extend and improve the OpenNMS platform. The Developers Guide is a good starting point for extending OpenNMS and using the ReST APIs f
```suggestion
                    <td style="border-top: none;">For developers who want to extend and improve the OpenNMS platform and use the ReST APIs for integration. Learn how to set up a development environment and get started with writing features for OpenNMS.</td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
>                  </tr>
The Welcome Guide section (lines 85-87) should be removed, as the link doesn't work, and I don't think we have a welcome guide anymore.

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
> +                            class="btn btn-secondary" role="button" style="width: 100%">OpenAPI doc</a></td>
```suggestion
                            class="btn btn-secondary" role="button" style="width: 100%">OpenAPI Docs</a></td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
> +                    <td style="border-top: none;">With OpenAPI doc, you can easily know how each OpenNMS RESTful API works. You can also test and generate client code from it.</td>
```suggestion
                    <td style="border-top: none;"> The OpenAPI docs explains how each OpenNMS RESTful API works. You can also test and generate client code from them.</td>
```

2021-04-23 18:17 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
> +                    <td style="border-top: none;">A graph interface of OpenNMS OpenAPI doc.</td>
```suggestion
                    <td style="border-top: none;">A graphical user interface of the OpenNMS OpenAPI docs.</td>
```

2021-04-23 18:47 UTC, jadyhou commented
> @jadyhou It would be good to update the other text on this screen. If it is an issue to update as part of this PR, let me know and I can create a separate ticket. I'd like to update the content on the rest of this screen too (i.e., the "Get in Contact" section and the "Software Management" section).

Hi Bonnie, I think it's okay to update other wording or outdated links on this page in this pull request. I can update the Jira say there are also other things we also updated.

2021-04-23 19:11 UTC, Bonrob2 commented
Thanks for updating this screen. It would be great to update the other sections as well:

Change "Get in Contact" to "Contact Us". 

Change "Web Chat" description text to: "Chat with us on Mattermost. The Discussion channel is a good place to reach users and developers."

Change "Discourse" description text to: "Community forum to get help, share ideas, and participate in OpenNMS development."

Under Software Management:

Change "Issue Tracker" description text to: "We use Jira to manage the software project: bugs, enhancements, features, and release management. Create your free account. You are welcome to participate."

Change "Continuous Integration" button link to the following: https://app.circleci.com/pipelines/github/OpenNMS/opennms

And the description text should be: "Running OpenNMS in production requires software quality gates provided by CircleCI, our CI/CD system. GitHub login required."

2021-04-23 20:58 UTC, Bonrob2 requested changes
Just two minor issues I had missed.

2021-04-23 20:58 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
> +                    <td style="border-top: none;">The OpenAPI docs explains how each OpenNMS RESTful API works. You can also test and generate client code from them.</td>
My bad, I missed removing the "s" on "explains".
```suggestion
                    <td style="border-top: none;">The OpenAPI docs explain how each OpenNMS RESTful API works. You can also test and generate client code from them.</td>
```

2021-04-23 20:58 UTC, Bonrob2 commented on opennms-webapp/src/main/webapp/includes/help-documentation.jsp
> +                    <td style="border-top: none;">A graphical user interface of the OpenNMS OpenAPI docs.</td>
```suggestion
                    <td style="border-top: none;">A graphical user interface for the OpenNMS OpenAPI docs.</td>
```

2021-04-23 21:00 UTC, Bonrob2 approved these changes
LGTM!

2021-04-26 15:06 UTC, cgorantla approved these changes

2021-04-27 12:46 UTC, jadyhou commented
> This should be `foundation-2021`, shouldn't it? So it makes it into Meridian 2021.

Thanks. I've created a pull request for backporting the Antora part to foundation-2021. Leave the OpenAPI and Swagger UI part in Develop.

2021-04-28 15:25 UTC, merged