NMS-13338: Add DnsDetctor docs
OpenNMS/opennms pull request #3445
Opened 2021-05-30 20:44 UTC by mfuhrmann

### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [x] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13338

2021-05-31 11:55 UTC, indigo423 reviewed
Minor changes

2021-05-31 11:55 UTC, indigo423 commented on docs/modules/operation/pages/provisioning/detectors/DnsDetector.adoc
> +This detector is build to test the availability of the _DNS service_ on remote IP interfaces.
```suggestion
This detector lets you find DNS services for monitoring in your network.
```

2021-05-31 11:55 UTC, indigo423 commented on docs/modules/operation/pages/provisioning/detectors/DnsDetector.adoc
> +The detector tests the service availability by sending a DNS query for A resource record types against the DNS server to test.
```suggestion
The DNS service is detected when the server responds to a DNS query for an A resource record.
You can customize the A record used in the query with the `lookup` configuration parameter.
```

2021-05-31 13:32 UTC, Bonrob2 requested changes

2021-05-31 13:32 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/DnsDetector.adoc
> +This detector is build to test the availability of the _DNS service_ on remote IP interfaces.
```suggestion
This detector lets you find DNS services to monitor in your network.
```
Please verify this update is correct.

2021-05-31 13:32 UTC, Bonrob2 commented on docs/modules/operation/pages/provisioning/detectors/DnsDetector.adoc
> +The detector can be simulated with the command line tool `host`:
```suggestion
Use the command line tool `host` to simulate the detector:
```

2021-06-02 21:31 UTC, mfuhrmann commented
@Bonrob2 @indigo423 It is more or less the text from the monitors. I thought I replaced the "monitoring" part against "detection". But looks like I forgot some. Thanks!

2021-06-03 12:43 UTC, Bonrob2 commented
> @Bonrob2 @indigo423 It is more or less the text from the monitors. I thought I replaced the "monitoring" part against "detection". But looks like I forgot some. Thanks!

> @Bonrob2 @indigo423 It is more or less the text from the monitors. I thought I replaced the "monitoring" part against "detection". But looks like I forgot some. Thanks!

Hi @mfuhrmann, I still see my previous suggestions for update, but otherwise it looks fine.

2021-06-07 12:30 UTC, Bonrob2 approved these changes

2021-06-14 10:26 UTC, indigo423 approved these changes
LGTM!

2021-06-16 14:13 UTC, indigo423 commented
@mfuhrmann you can go ahead and merge them 2 green approved reviewers is good enough :) After merge cleanup: Update the JIRA issue and delete the branch.

2021-06-16 14:14 UTC, indigo423 commented
@mfuhrmann you can go ahead and merge them 2 green approved reviewers is good enough :) After merge cleanup: Update the JIRA issue and delete the branch.

2021-06-17 19:21 UTC, merged