NMS-13294: Add Meridian installation guide
OpenNMS/opennms pull request #3448
Opened 2021-05-31 11:21 UTC by indigo423

Add Meridian repository installation instructions for CentOS 7 and CentOS 8.

### All Contributors

* [ ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

Added instructions installing the Meridian repositories. The credentials for Meridian repositories are added as requirements.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13294

2021-05-31 13:41 UTC, Bonrob2 requested changes
LGTM.

2021-05-31 13:41 UTC, Bonrob2 commented on docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
> +<1> Replace the `REPO_USER` and `REPO_PASS` with the credentials received with your Meridian subscription
```suggestion
<1> Replace the `REPO_USER` and `REPO_PASS` with your Meridian subscription credentials.
```

2021-05-31 13:41 UTC, Bonrob2 commented on docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
> +<1> Replace the `REPO_USER` and `REPO_PASS` with the credentials received from your OpenNMS subscription
```suggestion
<1> Replace the `REPO_USER` and `REPO_PASS` with your Meridian subscription credentials.
```

2021-06-01 12:55 UTC, RangerRick approved these changes
seems reasonable to me

2021-06-01 12:57 UTC, merged