NMS-13314: Prevent meta-data modification
OpenNMS/opennms pull request #3451
Opened 2021-06-01 11:51 UTC by fooker

Modification of meta-data was only intended to be done via requisitions.
The requisitions process will create, update and delete meta-data of a node
according to the values defined in a requisition. Changing the meta-data
after a requisition synchronization was never intended conceptually. It
suffered from loosing of meta-data after re-synchronization. Keeping the
data would require manual deletion in massive scale using the UI and
leads to desync with the expected values.

This also reverts #3291.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

2021-06-01 13:26 UTC, Bonrob2 requested changes
one minor change

2021-06-01 13:26 UTC, Bonrob2 commented on docs/modules/development/pages/rest/meta-data.adoc
>  == GETs (Reading Meta-Data)
```suggestion
== GETs (Reading Metadata)
```

2021-06-01 13:28 UTC, Bonrob2 requested changes
one more. :-)

2021-06-01 13:28 UTC, Bonrob2 commented on docs/modules/development/pages/rest/meta-data.adoc
> +You can qurey the actual metadata of nodes, interfaces, and services via REST endpoints.
```suggestion
You can query the actual metadata of nodes, interfaces, and services via REST endpoints.
```

2021-06-01 14:20 UTC, Bonrob2 approved these changes
LGTM!

2021-06-08 02:45 UTC, Naicisum commented
Code wise, I think this should go into H29 as it's a breaking change and H28 has been released. This API has been in the wild for a while and it is unknown who would be impacted by this change.

2021-06-08 07:03 UTC, indigo423 commented
> Code wise, I think this should go into H29 as it's a breaking change and H28 has been released. This API has been in the wild for a while and it is unknown who would be impacted by this change.

IIRC we try to follow semver.org and with the following guidelines:

> Given a version number MAJOR.MINOR.PATCH, increment the:
  * MAJOR version when you make incompatible API changes,
  * MINOR version when you add functionality in a backward-compatible manner, and
  * PATCH version when you make backward-compatible bug fixes.

2021-06-08 07:05 UTC, merged