NMS-13347: Fixed Minion entrypoint.sh
OpenNMS/opennms pull request #3476
Opened 2021-06-09 06:22 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-13347

2021-06-09 11:34 UTC, fooker requested changes

2021-06-09 11:34 UTC, fooker commented on opennms-container/minion/container-fs/entrypoint.sh
> +  find "${MINION_HOME}/etc/opennms.properties.d" -name '*.properties' | while read filename; do
```suggestion
  find "${MINION_HOME}/etc/opennms.properties.d" -name '*.properties' | while IFS= read -r -d '' filename; do
```

2021-06-09 15:26 UTC, swachter approved these changes
LGTM
(Such a lot of test code :smile:)

2021-06-14 09:46 UTC, indigo423 approved these changes
LGMT! Thanks for adding Minion startup test! 🎉

2021-06-14 11:17 UTC, merged