NMS-13294: Add Meridian repository description for Minion and Sentinel
OpenNMS/opennms pull request #3488
Opened 2021-06-14 15:14 UTC by indigo423

### All Contributors

* [ ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

2021-06-14 15:37 UTC, Bonrob2 requested changes
LGTM!

2021-06-14 15:37 UTC, Bonrob2 commented on docs/modules/deployment/pages/minion/centos-rhel7/install-minion.adoc
> +.Add repository and import GPG key
```suggestion
. Add repository and import GPG key.
```

2021-06-14 15:37 UTC, Bonrob2 commented on docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
> +.Add repository and import GPG key
```suggestion
. Add repository and import GPG key.
```

2021-06-14 17:34 UTC, mmahacek reviewed
Do we want to maintain duplicate repo instructions in Minion/Sentinel, or have those components just reference to use the same repo as the core server?  This would make future edits easier as there wouldn't be as many copies to have to keep in sync when.

2021-06-15 12:49 UTC, Bonrob2 commented
> Do we want to maintain duplicate repo instructions in Minion/Sentinel, or have those components just reference to use the same repo as the core server? This would make future edits easier as there wouldn't be as many copies to have to keep in sync when.

This makes sense to me.

2021-06-16 15:03 UTC, indigo423 commented
@mmahacek @Bonrob2 I have addressed your comment regarding duplication for the repository file.

2021-06-16 15:31 UTC, mmahacek approved these changes

2021-06-16 16:54 UTC, Bonrob2 approved these changes
LGTM!

2021-06-21 19:12 UTC, merged