NMS-12978: Add Prometheus Collectd Service configuration example
OpenNMS/opennms pull request #3542
Opened 2021-07-15 10:18 UTC by mfuhrmann

### All Contributors

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new or updated feature, is there documentation for the new behavior?
* [ ] If this is new code, are there unit and/or integration tests?
* [ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer has looked it over.

Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12978

2021-07-15 14:14 UTC, Bonrob2 requested changes
Minor change. I can't comment on whether the example works, but it looks good to me.

2021-07-15 14:14 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/collectors/prometheus.adoc
> +== Prometheus Node Exporter Collectd Service Configuration Example
```suggestion
== Prometheus Node Exporter Collectd service configuration example
```
We are starting to move towards using sentence capitalization for headings. In this case, though, we still have to capitalize Prometheus Node Exporter and Collectd, as we are using them as proper nouns in the docs.

2021-07-16 06:13 UTC, mfuhrmann commented
@Bonrob2 The example works. If you would read the collectd logs properly, then you should be able to write this code by yourself. But having it as a copy + paste version in the docs is a little bit easier (since this one is not included in the default collectd configuration) for the users.

2021-07-16 12:23 UTC, Bonrob2 approved these changes
Looks great!

2021-07-21 14:33 UTC, merged