NMS-13469: fix ReST queries for OnmsIpInterface snmpPrimary
OpenNMS/opennms pull request #3556
Opened 2021-07-23 18:48 UTC by RangerRick

This PR does a bunch of plumbing work to fix querying nodes and interfaces based on their SNMP primary status.

- add `OnmsIpInterface#getSnmpPrimary` and move the hibernate annotation to it to make ReST mapping happy, `#getIsSnmpPrimary` is left in place so that a bunch of code doesn't need changing (including end-user groovy code); this includes creating a `CharacterUserType` adapter for Hibernate
- change PrimaryType to not be an `Embedded` Hibernate column, instead just make it a property of `OnmsIpInterface` to avoid API changes
- refactor `PrimaryTypeAdapter` from Provisiond into `opennms-model` so it can be live with other type adapters
- fix internal HQL queries to use `.snmpPrimary` rather than `.isSnmpPrimary`
- update `PrimaryType#get` to accept a String _or_ Character/char
- add "snmpPrimary" checks to both the `NodeRestServiceIT` and `IpInterfaceRestServiceIT`
- add search properties for PrimaryType so Helm displays the choices

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13469

2021-07-24 16:10 UTC, fooker requested changes

2021-07-24 16:10 UTC, fooker commented on features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/model/IpInterfaceTopologyEntity.java
> +
```suggestion
    public IpInterfaceTopologyEntity(Integer id,
            InetAddress ipAddress, String isManaged, Character snmpPrimary, Integer nodeId,
            Integer snmpInterfaceId){
        this(id, ipAddress, isManaged, PrimaryType.get(snmpPrimary), nodeId, snmpInterfaceId);
    }

```

2021-07-27 11:47 UTC, christianpape approved these changes
LGTM.

2021-07-27 14:21 UTC, fooker approved these changes

2021-07-27 15:23 UTC, cgorantla reviewed
Looks good.
I see that we have this limitation of 1 char column on DB. 
That makes it hard to modify.

It would be good to add a test case on IpInterfaceDao for PrimaryType validation.

2021-07-28 18:32 UTC, merged