Minion doc tweak for scv.jce location
OpenNMS/opennms pull request #3583
Opened 2021-08-13 15:56 UTC by mmahacek

Small tweak to clarify the location of the scv.jce file in the docs.  Brought up due to a customer question to verify the file is in the application ETC folder, not the root system ETC folder.

### External References

* JIRA (Issue Tracker): none

2021-08-16 12:40 UTC, Bonrob2 approved these changes
LGTM!

2021-08-16 13:15 UTC, indigo423 commented
You PR invalidates: https://github.com/OpenNMS/opennms/blob/d6cf8d30397a104b430fe1f4266a20706d3667f1/docs/modules/deployment/pages/minion/install.adoc#configure-connectivity-to-the-core-instance

2021-08-16 13:16 UTC, indigo423 requested changes
Your PR invalidates this here:

![Screenshot 2021-08-16 at 15 18 58](https://user-images.githubusercontent.com/1095181/129571574-3cdf23a1-9d83-465d-8869-8c4fdf976067.png)

We would need to introduce MINION_HOME or SENTINEL_HOME globally, somewhere.

2021-08-16 15:17 UTC, mmahacek commented
> We would need to introduce MINION_HOME or SENTINEL_HOME globally, somewhere.

Fair point.  I don't think we define $OPENNMS_HOME in the docs, and that is used in many different locations.

2021-08-16 15:58 UTC, mmahacek commented
@indigo423 What do you think about adding a note like this to each of the install pages for the various components?
![image](https://user-images.githubusercontent.com/26419758/129593124-38fabb01-730a-4b40-9ff2-e5020be821f8.png)

2021-08-16 16:03 UTC, indigo423 commented
> @indigo423 What do you think about adding a note like this to each of the install pages for the various components?
> ![image](https://user-images.githubusercontent.com/26419758/129593124-38fabb01-730a-4b40-9ff2-e5020be821f8.png)

Yes, totally agree. I personally don't have a strong opinion on which variant. We can a) point the user to the directory and use a relative path or b) introduce for each component a `*_HOME` variable.

If we pick the path for the `*_HOME` variable it would be nice we really set them on installation so the copy & paste stuff works regardless of Debian/Ubuntu or CentOS/RHEL.

2021-08-16 16:12 UTC, mmahacek commented
> We already do this for core:

That only appears on a Cent install for me.  I don't see that file existing on a Ubuntu install I have.

2021-08-16 16:19 UTC, indigo423 commented
> > We already do this for core:
> 
> That only appears on a Cent install for me. I don't see that file existing on a Ubuntu install I have.

ok sweet, so my suggestion would be then we use `OPENNMS_HOME`, `SENTINEL_HOME` and `MINION_HOME` and open an additional issue to set these variables during RPM/DEB install correctly. In the meantime we can add a NOTE on top of each component and say for example SENTINE_HOME is `/opt/sentinel` on CentOS/RHEL and `/usr/share/sentinel` on Debian/Ubuntu. As soon we have the patch with the variables merged we can remove the note entirely and rely on the variable. What do you think?

2021-08-16 16:24 UTC, mmahacek commented
I think it would be helpful to have the variables set during install.  IMO, the reference to the path could permanently live on the install page for each product, but there wouldn't need to be a reference to the path on component/feature pages.

2021-08-23 09:56 UTC, indigo423 reviewed
We should be defensive and should use `${}`, especially with `_` and string concatenation.

2021-08-23 09:56 UTC, indigo423 commented on docs/modules/deployment/pages/minion/message-broker/activemq.adoc
> +The credentials are encrypted on disk in `$MINION_HOME/etc/scv.jce`.
```suggestion
The credentials are encrypted on disk in `${MINION_HOME}/etc/scv.jce`.
```

2021-08-23 09:56 UTC, indigo423 commented on docs/modules/deployment/pages/minion/message-broker/kafka.adoc
> +The credentials are encrypted on disk in `$MINION_HOME/etc/scv.jce`.
```suggestion
The credentials are encrypted on disk in `${MINION_HOME}/etc/scv.jce`.
```

2021-08-23 09:56 UTC, indigo423 commented on docs/modules/deployment/pages/sentinel/message-broker/activemq.adoc
> +NOTE: The credentials are encrypted on disk in `$SENTINEL_HOME/etc/scv.jce`.
```suggestion
NOTE: The credentials are encrypted on disk in `${SENTINEL_HOME}/etc/scv.jce`.
```

2021-08-23 09:56 UTC, indigo423 commented on docs/modules/deployment/pages/sentinel/message-broker/kafka.adoc
> +NOTE: The credentials are encrypted on disk in `$SENTINEL_HOME/etc/scv.jce`.
```suggestion
NOTE: The credentials are encrypted on disk in `${SENTINEL_HOME}/etc/scv.jce`.
```

2021-09-21 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3583) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3583) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS/opennms?pullRequest=3583) it.</sub>

2021-10-01 15:32 UTC, merged