NMS-10476: Document data types
OpenNMS/opennms pull request #3627
Opened 2021-09-08 18:30 UTC by mmahacek

### All Contributors

* [X] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [X] Have you made a comment in that issue which points back to this PR?
* [X] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [X] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10476

2021-09-13 20:36 UTC, Bonrob2 requested changes

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +{page-component-title} stores both of these the same, and `COUNTER`, `COUNTER32`, and `COUNTER64` may be used interchangeably in data collection definitions to refer to this data type.
```suggestion
{page-component-title} stores both of these the same, and you can use `COUNTER`, `COUNTER32`, and `COUNTER64` interchangeably in data collection definitions to refer to this data type.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +When a counter reaches the upper limit, the value will reset to zero and continue incrementing.
```suggestion
When a counter reaches the upper limit, the value resets to zero and continues to increment.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +{page-component-title} stores both of these the same, and `GAUGE`, `GAUGE32`, and `GAUGE64` may be used interchangeably in data collection definitions to refer to this data type.
```suggestion
{page-component-title} stores both of these the same, and you can use `GAUGE`, `GAUGE32`, and `GAUGE64` interchangeably in data collection definitions to refer to this data type.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +The integers type represents values that represent a number between -2^31 and 2^31-1 (-2147483648 to 2147483647 decimal).
```suggestion
The integer type represents values that represent a number between -2^31 and 2^31-1 (-2147483648 to 2147483647 decimal).
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +{page-component-title} stores both of these the same, and `INTEGER`, `INTEGER32`, and `INTEGER64` may be used interchangeably in data collection definitions to refer to this data type.
```suggestion
{page-component-title} stores both of these the same, and you can use `INTEGER`, `INTEGER32`, and `INTEGER64` interchangeably in data collection definitions to refer to this data type.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +Integers may also be used to represent a named-number enumeration status value.
```suggestion
You can also use integers to represent a named-number enumeration status value.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +Network addresses should be represented using a `STRING` value.
```suggestion
Use a `STRING` value to represent network addresses.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +The octetstring type represents arbitrary binary or textual data presented as a hex string.
```suggestion
The OctetString type represents arbitrary binary or textual data presented as a hex string.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +The Opaque type is provided solely for backward-compatibility, and shall not be used for newly-defined object types.
```suggestion
The Opaque type is provided solely for backward-compatibility.
Do not use it for newly-defined object types.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +Stored values can be retrieved using the xref:development:rest/resources.adoc[].
```suggestion
Retrieve stored values with the xref:development:rest/resources.adoc[Resources API].
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +The counter type represents values that that continue to increase over time.
```suggestion
The counter type represents values that continue to increase over time.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +This type may be presented from the device with a non-negative integer with a maximum of either a 32-bit or 64-bit upper limit.
```suggestion
The device may present this type with a non-negative integer with a maximum of either a 32-bit or 64-bit upper limit.
```

2021-09-13 20:36 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +This type may be presented from the device with a non-negative number with a maximum of either a 32-bit or 64-bit upper limit.
```suggestion
The device may present this type with a non-negative number with a maximum of either a 32-bit or 64-bit upper limit.
```

2021-09-20 15:34 UTC, mmahacek commented
@Bonrob2 I have this being added to the Operation section for collection.  Should it be moved into the Reference section instead?

2021-09-20 15:34 UTC, mmahacek commented
@Bonrob2 I have this being added to the Operation section for collection.  Should it be moved into the Reference section instead?

2021-09-20 15:49 UTC, Bonrob2 commented
> @Bonrob2 I have this being added to the Operation section for collection. Should it be moved into the Reference section instead?

It makes sense in the reference section, but we would want to keep a stub in the operations section where we could put an example, if appropriate, then cross reference to the reference section.

2021-09-21 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS/opennms?pullRequest=3627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS/opennms?pullRequest=3627) it.</sub>

2021-10-01 17:08 UTC, Bonrob2 requested changes
Just one change. Otherwise, looks good.

2021-10-01 17:08 UTC, Bonrob2 commented on docs/modules/operation/pages/performance-data-collection/data-types.adoc
> +Do not use it for newly-defined object types.
```suggestion
Do not use it for newly defined object types.
```

2021-10-01 21:04 UTC, merged