NMS-13684: Copy Jetty SSL info from Discourse
OpenNMS/opennms pull request #3870
Opened 2021-11-16 15:49 UTC by mmahacek

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13684

2021-11-19 21:29 UTC, indigo423 requested changes
To be copy & paste friendly, we remove the leading `$` from the console inputs.

2021-11-19 21:31 UTC, mmahacek commented
> To be copy & paste friendly, we remove the leading `$` from the console inputs.

Okay.   This is still an early draft that I'm working on cleaning up.

2021-11-19 21:31 UTC, indigo423 requested changes

2021-11-19 21:31 UTC, indigo423 commented on docs/modules/reference/pages/configuration/ssl.adoc
> +`
It looks like there are some markdown leftovers for the console in- and outputs.

2021-11-19 21:32 UTC, indigo423 commented
> > To be copy & paste friendly, we remove the leading `$` from the console inputs.
> 
> Okay. This is still an early draft that I'm working on cleaning up.

ok got it, probably was too early :)

2022-04-26 13:23 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/https/https-server.adoc
> +Copy this to `$\{OPENNMS_HOME}/etc` and remove comment tags for the section "Add HTTPS Support"
```suggestion
Copy this to `$\{OPENNMS_HOME}/etc` and remove comment tags for the section "Add HTTPS Support".
```

2022-04-26 13:23 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/https/https-server.adoc
> +For the first question ("What is your first and last name"), enter the fully-qualified domain name by which people will be accessing your OpenNMS server's web UI.
```suggestion
For the first question ("What is your first and last name"), enter the fully-qualified domain name by which people will access your OpenNMS server's web UI.
```

2022-04-26 13:32 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/https/https-server.adoc
> +Answer the remaining questions according to the specifics of your organization and locality.
```suggestion
Answer the remaining questions according to the specifics of your organization and location.
```

2022-04-26 13:33 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/https/https-server.adoc
> +The example below specifies 731 days, which will make the key valid for two years (accounting for a possible leap year).
```suggestion
The example below specifies 731 days, which makes the key valid for two years (accounting for a possible leap year).
```

2022-04-26 13:34 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/https/https-server.adoc
> +The steps to configure OpenNMS to start a Jetty HTTPS listener on port 8443 do not disable the plain HTTP listener that is present by default on port 8980.
```suggestion
The steps to configure OpenNMS to start a Jetty HTTPS listener on port 8443 do not disable the plain-HTTP listener that is present by default on port 8980.
```

2022-05-03 20:00 UTC, mmahacek commented
@indigo423 Can you clear your requested changes on this PR to get it into the next release?

2022-05-18 19:55 UTC, merged