NMS-13759: Split asset topology provider docs
OpenNMS/opennms pull request #3880
Opened 2021-11-17 19:30 UTC by mfuhrmann

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13759

2021-11-17 21:09 UTC, Bonrob2 reviewed
Just a few changes, otherwise looks good.

2021-11-17 21:09 UTC, Bonrob2 commented on docs/modules/operation/pages/topology/asset-topology-provider/create-asset-based-topologies-karaf.adoc
> +-a, --assetLayers : Comma-separated list of asset layers (Default: asset-region,asset-building,asset-rack) +
```suggestion
-a, --assetLayers : Comma-separated list of asset layers (Default: asset-region, asset-building, asset-rack) +
```

2021-11-17 21:09 UTC, Bonrob2 commented on docs/modules/operation/pages/topology/asset-topology-provider/create-asset-based-topologies-karaf.adoc
> +| -i, --providerId : Unique providerId of asset topology to regenerate (Default: asset)
```suggestion
| -i, --providerId : Unique providerId of asset topology to regenerate (Default: asset).
```

2021-11-17 21:09 UTC, Bonrob2 commented on docs/modules/operation/pages/topology/asset-topology-provider/introduction.adoc
> +The layer 0 graph is called `asset-region`, the layer 1 graph is called `asset-building`, and the layer 2 graph is called `nodes`.
```suggestion
The layer 0 graph is called `asset-region`; the layer 1 graph is called `asset-building`; and the layer 2 graph is called `nodes`.
```

2021-11-17 21:09 UTC, Bonrob2 commented on docs/modules/operation/pages/topology/asset-topology-provider/node-filtering.adoc
> +In many cases, it is desirable to control which nodes are included or excluded from a topology.
```suggestion
In many cases, it is desirable to control which nodes a topology includes or excludes.
```

2021-11-17 21:09 UTC, Bonrob2 commented on docs/modules/operation/pages/topology/asset-topology-provider/view-additional-notes.adoc
> +The label field does not need to be the same as the providerId that the ReST API uses for the installation or removal of a topology.
```suggestion
The label field does not need to be the same as the providerId that the REST API uses for the installation or removal of a topology.
```

2021-11-22 00:46 UTC, Bonrob2 submitted a review, later dismissed
LGTM!

2021-11-22 17:10 UTC, mmahacek requested changes

2021-11-22 17:10 UTC, mmahacek commented on docs/modules/operation/pages/topology/asset-topology-provider/configuration.adoc
> +|===
```suggestion
The configuration file contains each of the graph definitions as properties in the form:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configs>
    <config>
        <label>Asset Topology Provider</label><1>
        <breadcrumb-strategy>SHORTEST_PATH_TO_ROOT</breadcrumb-strategy><2>
        <provider-id>asset</provider-id><3>
        <preferred-layout>Grid Layout</preferred-layout><4>
        <filters><5>
            <filter>asset-region=South</filter>
        </filters>
        <layers><6>
            <layer>asset-region</layer>
            <layer>asset-building</layer>
            <layer>asset-rack</layer>
        </layers>
    </config>
</configs>
----
<1> The name that shows up on the topology menu (must be unique).
<2> Breadcrumb strategy used to display breadcrumbs above each graph.
<3> The unique name of the provider - used as a handle to install and remove the topology.
<4> Preferred node layout in generated graphs.
<5> List of filters to apply. Filters determine the nodes to include in the graph. See xref:operation:topology/asset-topology-provider/node-filtering.adoc[node filtering].
<6> List of asset layers (in order). See xref:operation:topology/asset-topology-provider/asset-layers.adoc[asset layers].
```

2021-11-22 17:10 UTC, mmahacek commented on docs/modules/operation/pages/topology/asset-topology-provider/create-asset-based-topologies-karaf.adoc
> +| all : display detailed view including --uriParams string
```suggestion
| --all : display detailed view including --uriParams string
```

2021-11-22 17:10 UTC, mmahacek commented on docs/modules/operation/pages/topology/asset-topology-provider/create-asset-based-topologies-karaf.adoc
> +If you simply type `asset-topology:create`, a default topology with providerId asset is created.
```suggestion
If you simply type `opennms:asset-topo-create`, a topology with default settings is created.
```

2021-11-22 17:10 UTC, mmahacek commented on docs/modules/operation/pages/topology/asset-topology-provider/create-asset-based-topologies-karaf.adoc
> +-b, --breadcrumbStrategy : Breadcrumb strategy (Default: SHORTEST_PATH_TO_ROOT) +
```suggestion
-b, --breadcrumbStrategy : Breadcrumb strategy (Default: SHORTEST_PATH_TO_ROOT)
```

2021-11-23 18:04 UTC, mfuhrmann commented
@Bonrob2 @mmahacek Thanks for reviewing and improving!

2021-12-08 19:06 UTC, mfuhrmann commented
Oh Oh. I am not sure if the rebase did what I wanted...

2021-12-08 19:18 UTC, mmahacek commented
😂 Which branch did you rebase against?

2021-12-08 19:45 UTC, mfuhrmann commented
@mmahacek `foundation-2021`

2021-12-08 19:47 UTC, mmahacek commented
I was being somewhat rhetorical as that's probably what was intended, but why your copy of the repo has all these commits that aren't in the main foundation branch is beyond me.  Given today is a release day, does @RangerRick have any insight?

2021-12-08 19:49 UTC, mfuhrmann commented
Don't spend too much time on that. I can create a new PR for this.

2021-12-08 19:53 UTC, RangerRick commented
Release day already happened, so that's academic.  :)

The problem appears to be that you rebased against `foundation-2021` from a bit ago, because if I try to merge the latest 2021 to your branch, there's a _lot_ of changes.  Just one conflict though.

You might want to try rebasing again (make sure you do it against `origin/foundation-2021` after doing a `git fetch` or `git pull` just to make sure you're in sync) and see if that helps.

2021-12-08 20:07 UTC, mfuhrmann commented
That was fun... NOT ;-)
Will create a new PR. See you later

2021-12-08 20:07 UTC, closed without merging