NMS-13650: Add tracing for Twin modules.
OpenNMS/opennms pull request #3890
Opened 2021-11-18 21:05 UTC by cgorantla

Add distributed tracing to Twin.
Route twin related logs to ipc.log

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13650

2021-11-23 11:20 UTC, fooker requested changes
Can the code to create the `tracingOperationKey` be shared across the implementations and across publisher and subscriber?

2021-11-23 11:20 UTC, fooker commented on core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/AbstractTwinPublisher.java
> +        this.tracer = this.tracerRegistry.getTracer();
```suggestion
        this(localTwinSubscriber, localTwinSubscriber.getTracerRegistry);
```

2021-11-24 20:17 UTC, fooker approved these changes

2021-11-29 21:43 UTC, RangerRick approved these changes

2021-11-30 19:57 UTC, RangerRick approved these changes

2021-11-30 20:00 UTC, merged