PE-169 : [xmp-config.xml] - migrate xmp-config.xml to the new CM
OpenNMS/opennms pull request #3909
Opened 2021-11-25 15:44 UTC by psuthar-opennms

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/PE-169

2021-11-25 15:53 UTC, freddy61025 requested changes
some code cleanup and recover deleted entry.

2021-11-25 15:53 UTC, freddy61025 commented on features/config/upgrade/src/main/resources/changelog-cm/29.0.0/changelog-cm.xml
> -    <changeSet author="dherdt" id="1.0-register-jmxconfig">
you didn't do the rebase properly.

2021-11-25 15:53 UTC, freddy61025 commented on features/config/upgrade/src/main/resources/changelog-cm/29.0.0/changelog-cm.xml
> -    <changeSet author="dherdt" id="1.0-register-jmxconfig">
Some of changes are removed by you branch.

2021-11-25 15:53 UTC, freddy61025 commented on opennms-config/src/main/resources/META-INF/opennms/applicationContext-commonConfigs.xml
>    <bean id="databaseSchemaConfigFactory-init" class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
why add an extra line here?

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/collector/XmpCollector.java
> +import org.springframework.beans.factory.annotation.Autowired;
remove unused import

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/config/XmpPeerFactory.java
> +        //XmpConfigFactory.init();
remove comments

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/detector/XmpDetector.java
> +
should define private

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/detector/XmpDetector.java
> +            //XmpConfigFactory.init();
comments

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/monitor/XmpMonitor.java
>      /**
private

2021-11-25 15:53 UTC, freddy61025 commented on protocols/xmp/src/test/java/org/opennms/netmgt/protocols/xmp/collector/XmpCollectorComplianceTest.java
unused

2021-11-25 17:47 UTC, psuthar-opennms reviewed
All review comments implemented

2021-11-26 20:00 UTC, freddy61025 approved these changes

2021-11-26 20:01 UTC, merged