NMS-13709: Added scheduler for flow thresholding and persistence
OpenNMS/opennms pull request #3920
Opened 2021-11-29 13:36 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-13709

2021-11-29 21:23 UTC, RangerRick approved these changes

2021-12-01 08:19 UTC, fooker requested changes

2021-12-01 08:19 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +            }
These should move up a little to just wrap the session cache access.

2021-12-01 09:50 UTC, fooker approved these changes

2021-12-01 09:50 UTC, merged