NMS-13812: Add default RRD package for BMP telemetry persistence
OpenNMS/opennms pull request #3941
Opened 2021-12-02 20:48 UTC by indigo423

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

## Reviewers hint

I have targeted the PR for foundation-2021 cause this is the first release we introduced our own implementation for persisting BMP telemetry data and is a bug in our default shipped configuration. We can easily move it forward to release-29.x branch if it is not important enough to break our point release policy for Meridian and config changes.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13812

2021-12-02 22:39 UTC, fooker submitted a review, later dismissed

2021-12-03 01:35 UTC, cgorantla requested changes
This is not required  on `BMP-Persisting-Adapter` but only needed on `BMP-Telemetry-Adapter`

2021-12-03 23:21 UTC, indigo423 commented
> This is not required on `BMP-Persisting-Adapter` but only needed on `BMP-Telemetry-Adapter`

too many adapters :) Fixed! Thank you!

2021-12-06 14:38 UTC, cgorantla approved these changes

2021-12-06 18:01 UTC, RangerRick approved these changes
don't see why not

2021-12-06 20:14 UTC, merged