NMS-13855: Add ifName to strings.properties
OpenNMS/opennms pull request #3994
Opened 2021-12-13 15:51 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-13855

Test can be added when data collection is done.

2021-12-14 14:54 UTC, RangerRick approved these changes

2021-12-15 08:50 UTC, fooker requested changes

2021-12-15 08:50 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +                                                                                                                  application.getKey().iface,
This should use the `ifName`, too. Using the name would stabilize the name and not depend on internal IDs.

2021-12-15 14:56 UTC, fooker approved these changes

2021-12-15 14:57 UTC, merged