NMS-13758: Split Database Reports docs into multiple pages
OpenNMS/opennms pull request #4085
Opened 2022-01-10 19:28 UTC by mfuhrmann

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13758

2022-01-10 19:30 UTC, mfuhrmann commented
I had a talk with @indigo423 about this document. Most of the stuff is outdated and he is pretty sure it does not work as documented. For now, it doesn't make sense to spend too much time on it. I've followed @indigo423 advice to just split it like this for now.

2022-01-10 19:55 UTC, Bonrob2 approved these changes
Approval retracted, I realized why the nav seemed off, so have updated the heading levels. Please verify they are rendering correctly in the Table of Contents. Each file has to start with a single "=" in order to build properly.

2022-01-10 22:43 UTC, Bonrob2 requested changes
Headings were the wrong level.

2022-01-10 22:43 UTC, Bonrob2 commented on docs/modules/operation/pages/database-reports/pdf-reports-grafana.adoc
> +== Creating PDF reports from Grafana dashboards using {page-component-title}
```suggestion
= Creating PDF reports from Grafana dashboards using {page-component-title}
```

2022-01-10 22:43 UTC, Bonrob2 commented on docs/modules/operation/pages/database-reports/pdf-reports-grafana.adoc
> +=== Before you begin
```suggestion
== Before you begin
```

2022-01-10 22:43 UTC, Bonrob2 commented on docs/modules/operation/pages/database-reports/pdf-reports-grafana.adoc
> +=== Configure the Grafana endpoint
```suggestion
== Configure the Grafana endpoint
```

2022-01-10 22:43 UTC, Bonrob2 commented on docs/modules/operation/pages/database-reports/pdf-reports-grafana.adoc
> +=== Create a PDF of a Grafana dashboard
```suggestion
== Create a PDF of a Grafana dashboard
```

2022-01-23 13:14 UTC, mfuhrmann commented
If green, feel free to merge.

2022-01-24 13:30 UTC, Bonrob2 approved these changes

2022-01-24 13:31 UTC, merged