NMS-13811: Troubleshooting flows: basic
OpenNMS/opennms pull request #4271
Opened 2022-02-17 21:07 UTC by Bonrob2

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13811

2022-02-18 14:32 UTC, swachter requested changes
The Grafana-Templating issue needs some overhaul.

2022-02-18 15:48 UTC, Bonrob2 commented on docs/modules/operation/pages/flows/troubleshooting.adoc
> +. Start OpenNMS.
Thanks. I will remove this section.

2022-02-23 19:34 UTC, swachter approved these changes
LGTM

2022-02-23 19:54 UTC, mmahacek reviewed
a couple minor suggestions, but nothing I'd count as blocking

2022-02-23 19:54 UTC, mmahacek commented on docs/modules/operation/pages/flows/troubleshooting.adoc
> +[source, curl]
```suggestion
[source, console]
```

2022-02-23 19:54 UTC, mmahacek commented on docs/modules/operation/pages/flows/troubleshooting.adoc
> +curl "https://Your Endpoint-es.logit.io/_cat/indices?v&apikey=Your-API-Key"
I'd use a more properly formatted URL example
```suggestion
curl "https://your-es-server.hostname:9200/_cat/indices?v&apikey=Your-API-Key"
```

2022-02-28 19:01 UTC, Bonrob2 commented
@mmahacek  I updated based on your feedback, but lost the approval for the PR. Could you approve so I can merge?

2022-02-28 19:06 UTC, mmahacek approved these changes

2022-02-28 19:13 UTC, merged