NMS-14065: Document missing handlers
OpenNMS/opennms pull request #4392
Opened 2022-03-17 21:30 UTC by Bonrob2

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

2022-03-17 21:32 UTC, Bonrob2 commented
@jeffgdotorg , documentation based on what you wrote in the confluence document. The parameters aren't documented in the various plugin repos ... that would have to come under separate Jiras. Let me know if this is sufficient. 
@mmahacek , I'll have you review the non-draft PR, as there might be a lot of changes. :-)

2022-03-22 15:22 UTC, jeffgdotorg requested changes
See review comments.

2022-03-22 15:22 UTC, jeffgdotorg commented on docs/modules/reference/pages/provisioning/handlers/http.adoc
> +The HTTP(S) handler imports a properly-formatted requisition definition from an XML file stored remotely on a web server.
Can we say "from an XML document served by a remote web server"?

2022-03-22 15:22 UTC, jeffgdotorg commented on docs/modules/reference/pages/provisioning/handlers/requisition-plugin.adoc
> +Each of these plugins has a handler that invokes the plugin with default settings, and imports requisitions generated by that plugin.
Each of these plugins has a handler that invokes the plugin with default settings.
Some plugins accept options in the form of query parameters, which shape the requisitions generated by that plugin and imported by Provisiond.

2022-03-23 19:24 UTC, Bonrob2 commented
@indigo423 , since Mark is away, could you review? I've updated based on Jeff's feedback.

2022-03-23 19:47 UTC, mmahacek reviewed
There is talk of "plugins". Are those the http/VMware handlers or something else?

2022-03-23 20:06 UTC, Bonrob2 commented
> There is talk of "plugins". Are those the http/VMware handlers or something else?

The plugins are OpenDaylight, ACI, PRIS. But since they are experimental, Jeff suggested not documenting them, but having the "Requisition Plugins" topic for those who might know about them. We could consider linking to them in GitHub.

2022-03-23 20:11 UTC, mmahacek commented
Personally, if there aren't links to them, I'd leave the mention of them out. As a user, it's confusing in the current state to not have anything describing what plugins are or that they're currently experimental. Should probably at least mention that fact.

2022-03-23 20:15 UTC, Bonrob2 commented
Given that we have an entire set of documentation for "nephron" which is also experimental, I'm inclined to link to them in GitHub.

2022-03-23 20:46 UTC, mmahacek approved these changes

2022-03-23 21:03 UTC, merged