NMS-13802: Add docs for Device Config
OpenNMS/opennms pull request #4517
Opened 2022-04-07 20:50 UTC by cgorantla

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13802

2022-04-08 15:42 UTC, Bonrob2 requested changes
Looking good. We may need to restructure the content once the UI documentation side is done, but we can do that as part of that Jira.

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +see xref:development:rest/device_config.adoc[Device Config Monitor].
```suggestion
(See xref:development:rest/device_config.adoc[Device Config Monitor].)
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +== Retrieve/Trigger Device Config Backup from Karaf shell
```suggestion
== Retrieve/trigger device configuration backup from Karaf shell
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +Device Config can also be triggered/retrieved from karaf shell.
```suggestion
You can also trigger/retrieve a device configuration from the Karaf shell.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/nav.adoc
> +** xref:service-assurance/monitors/DeviceConfiMonitor.adoc[]
verifying spelling ... the file is DeviceConfiMonitor.adoc, but chapter title is "DeviceConfigMonitor" (see comment line 2 in DeviceConfiMonitor.adoc file.

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> += DeviceConfigMonitor
```suggestion
= DeviceConfigMonitor
```
Is this correct name? Could we rename .adoc file and the nav file entry  to include the "g"?

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +This Monitor tries to retrieve config from the network device and will show corresponding status based on whether config retrieval succeeded or not.
```suggestion
This monitor tries to retrieve configuration from the network device and shows the status of that retrieval (success, failed, and so on).
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +| Script file that needs to be used to retrieve config.
```suggestion
| Script file to use to retrieve configuration.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +| If Device has multiple configs, config-type should be specified with each service.
```suggestion
| If device has multiple configurations, specify the config-type with each service.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +| Schedule for fetching config in the form of cron expression.
```suggestion
| Schedule to fetch configuration, in the form of cron expression.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +example configuration on how to configure the DeviceConfigMonitor in the `poller-configuration.xml`.
```suggestion
Example for how to configure the DeviceConfigMonitor in the `poller-configuration.xml`.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +For Device Config Monitor service, interval is configured to be 300secs and schedule is a cron expression. Default
```suggestion
The Device Config Monitor service uses an the interval of 300secs and a cron expression for the schedule.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +cron expression runs every 24 hrs at 12.00am (0 0 0 * * ?). Monitor retrieves the Device config when the next trigger
```suggestion
The default cron expression runs every 24 hrs at 12.00am (0 0 0 * * ?). 
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfiMonitor.adoc
> +from schedule falls within the interval.
```suggestion
The monitor retrieves the device configuration when the next trigger from the schedule falls within the interval.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/development/pages/rest/device_config.adoc
> +| Retrieves all the configs sorted by lastUpdated.
```suggestion
| Retrieves all the configurations, sorted by lastUpdated.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/development/pages/rest/device_config.adoc
> +| Retrieves all the configs for the specific interface.
```suggestion
| Retrieves all the configurations for the specific interface.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/development/pages/rest/device_config.adoc
> +| Retrieves the latest config for all the devices.
```suggestion
| Retrieves the latest configuration for all the devices.
```

2022-04-08 15:42 UTC, Bonrob2 commented on docs/modules/development/pages/rest/device_config.adoc
> +.Trigger Device Config backup
```suggestion
.Trigger device configuration backup
```

2022-04-12 14:19 UTC, cgorantla commented on docs/modules/development/pages/rest/device_config.adoc
> +Use the Device Config Rest API to fetch existing configs and trigger retrieval of the device configs and is in `api/v2` endpoint.
Removed

2022-04-12 14:21 UTC, cgorantla commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +.Configure opennms-deviceconfig-sink feature
It's applicable for both. Added `({page-component-title}/Minion)`

2022-04-12 14:44 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
>  == Poller configuration
= Poller configuration

Title level needs to be updated, as the table of contents did not build properly.

2022-04-12 14:46 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +(See xref:development:rest/device_config.adoc[Device Config Monitor].)
(See xref:development:rest/device_config.adoc[Device Config Rest API].

2022-04-12 14:48 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
> +The Device Config Monitor service uses an the interval of 300secs and a cron expression for the schedule.
The Device Config Monitor service uses an interval of 300secs and a cron expression for the schedule.

2022-04-12 15:02 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +(See xref:development:rest/device_config.adoc[Device Config Rest API].
```suggestion
(See xref:development:rest/device_config.adoc[Device Config Rest API].)
```

2022-04-12 15:03 UTC, Bonrob2 approved these changes
I missed the closing parenthesis, so just added it and committed it. Everything else looks good. Thanks!

2022-04-12 15:06 UTC, merged