NMS-14143: Add blocking option on trigger
OpenNMS/opennms pull request #4581
Opened 2022-04-22 18:19 UTC by cgorantla

POST should handle all requests and provide multi response when something fails
`device-config-get` karaf command will not persist but returns response ( for testing)
`device-config-trigger-backup` will trigger backup and persists the response.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14143
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14176

2022-04-22 18:38 UTC, synqotik commented on features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/BackupResponseDTO.java
> +    private BackupRequestDTO backupRequestDTO;
Change member variable name to `request` so that the serialized Json response looks more appropriate.

2022-04-22 18:49 UTC, synqotik submitted a review, later dismissed
Looks good - just one small comment.

2022-04-25 21:27 UTC, mmahacek commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +                Whether persist config or not
```suggestion
                Whether to persist config or not
```

2022-04-25 21:30 UTC, mmahacek requested changes
Grammar check on DCB command help

2022-04-25 21:30 UTC, mmahacek commented on features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DcbGetCommand.java
> +    @Option(name = "-p", aliases = "--persist", description = "Whether persist config or not")
```suggestion
    @Option(name = "-p", aliases = "--persist", description = "Whether to persist config or not")
```

2022-04-25 21:30 UTC, mmahacek commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +                Whether persist config or not
```suggestion
                Whether to persist config or not
```

2022-04-25 21:30 UTC, mmahacek commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +                Whether persist config or not
```suggestion
                Whether to persist config or not
```

2022-04-25 21:30 UTC, mmahacek commented on features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DcbTriggerCommand.java
> +    @Option(name = "-p", aliases = "--persist", description = "Whether persist config or not")
```suggestion
    @Option(name = "-p", aliases = "--persist", description = "Whether to persist config or not")
```

2022-04-25 22:47 UTC, mmahacek reviewed
The documentation portion looks good to me.  (Can't comment on the rest)

2022-04-26 02:08 UTC, synqotik approved these changes
LGTM

2022-04-26 02:11 UTC, merged