NMS-13574: External Authentication Documentation
OpenNMS/opennms pull request #4595
Opened 2022-04-25 23:01 UTC by mmahacek

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13574

2022-04-25 23:04 UTC, mmahacek commented
Note: needs https://github.com/OpenNMS/opennms/pull/3870 merged first to clear the antora build

2022-05-03 21:56 UTC, Bonrob2 requested changes
Minor changes.

2022-05-03 21:56 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +If you have an existing directory for authenticating users, {page-component-title} can be configured to utilize that system for granting users access to login, in addition to allowing login from user
```suggestion
If you have an existing directory for authenticating users, {page-component-title} can be configured to use that system to grant users access to log in, in addition to allowing log in from users defined directly within your {page-component-title} server.
```

2022-05-03 21:56 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +This has a significant implication in that you cannot filter a user search by nested group membership, and most installs tend not to be fully hierarchical (User's DN doesn't cite a home group).
```suggestion
This has a significant implication in that you cannot filter a user search by nested group membership, and most installs tend not to be fully hierarchical (user's DN doesn't cite a home group).
```

2022-05-03 21:56 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +NOTE: If your directory requires a SSL connection, and is signed with a private certificate authority, make sure to add the certificates to your xref:admin/https/https-client.adoc[truststore].
```suggestion
NOTE: If your directory requires an SSL connection, and is signed with a private certificate authority, make sure to add the certificates to your xref:admin/https/https-client.adoc[truststore].
```

2022-05-03 21:56 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +After making any changes to Spring Security configuration, {page-component-title} must be restarted for the changes to take effect.
```suggestion
After making any changes to Spring Security configuration, you must restart {page-component-title} for the changes to take effect.
```

2022-05-03 21:56 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +If you've gotten all the details right, you'll be able to log in to the webapp with your directory credentials after restarting OpenNMS.
```suggestion
If you have all the details right, you'll be able to log in to the webapp with your directory credentials after restarting OpenNMS.
```

2022-05-04 17:46 UTC, ProjectJYL submitted a review, later dismissed
LGTM

2022-05-18 21:10 UTC, Bonrob2 requested changes
Minor changes. It looks great.

2022-05-18 21:10 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +If you have an existing directory for authenticating users, {page-component-title} can be configured to use that system to grant users access to log in, in addition to allowing log in from users defi
```suggestion
If you have an existing directory for authenticating users, you can configure {page-component-title} to use that system to grant users access to log in, in addition to allowing log in from users defined directly within your {page-component-title} server.
```

2022-05-18 21:10 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +The Spring Security configuration can be modified without making large, invasive changes to the main context file.
```suggestion
You can modify the Spring Security configuration without making large, invasive changes to the main context file.
```

2022-05-18 21:10 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/external-auth.adoc
> +By defining `groupToRoleMap` entries, groups in your directory can be mapped to one or more security roles to determine what level of access the user should be granted.
```suggestion
By defining `groupToRoleMap` entries, groups in your directory can be mapped to one or more security roles to determine what level of access to grant to the user.
```

2022-06-02 20:45 UTC, Bonrob2 approved these changes
LGTM!

2022-06-06 17:56 UTC, merged