NMS-14109: Grafana box renders raw JS when Grafana behind reverse proxy with SSO
OpenNMS/opennms pull request #4613
Opened 2022-04-28 16:22 UTC by aramosvizcarra

Added extra set of properties that will only be used to generate the links url to access grafana datasources. Will use original api settings if they are not declared or blank.

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14109

2022-04-29 15:43 UTC, jeffgdotorg requested changes
Just some doc cleanup, otherwise this looks great and worked in my testing.

2022-04-29 15:43 UTC, jeffgdotorg commented on docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
> +
Please update the screenshot with the attached one
![Screenshot 2022-04-29 at 11-36-02 OpenNMS Web Console](https://user-images.githubusercontent.com/1209268/165978246-f8af6177-be87-4c91-9401-b19d068c645a.png)
.

2022-04-29 17:13 UTC, Bonrob2 requested changes
additional minor changes to the docs.

2022-04-29 17:13 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
> +| The protocol used to build each dashboard link url.
```suggestion
| The protocol used to build each dashboard link URL.
```

2022-04-29 17:13 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
> +| Hostname used to build each dashboard link url.
```suggestion
| Hostname used to build each dashboard link URL.
```

2022-04-29 17:13 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
> +| The port used to build each dashboard link url.
```suggestion
| The port used to build each dashboard link URL.
```

2022-04-29 17:13 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
> +| The Grafana base path used to build each dashboard link url.
```suggestion
| The Grafana base path used to build each dashboard link URL.
```

2022-05-02 15:04 UTC, aramosvizcarra commented
> Should this be rebased to `foundation-2022` or does the SSO stuff not affect earlier releases?

I think so, @jeffgdotorg  probably know for sure.

2022-05-03 22:00 UTC, Bonrob2 submitted a review, later dismissed
Docs LGTM!

2022-05-05 11:10 UTC, aramosvizcarra commented
Created a new PR since I had to rebase to foundation-2022
https://github.com/OpenNMS/opennms/pull/4654

2022-05-05 11:10 UTC, closed without merging