NMS-14208: upgrade Groovy to latest 2.x
OpenNMS/opennms pull request #4631
Opened 2022-05-02 20:15 UTC by RangerRick

This PR upgrades our embedded Groovy to the latest 2.x -- 2.5.16 -- which was recently updated in March.

2.5, in general, should be almost entirely source-compatible with the version we'd been using/embedding in OpenNMS.
The biggest changes have been structural (how the Maven project is published, some things being pulled out into "optional" dependencies, etc.)

This patch _should_ provide a version that's functionally equivalent to what we already were using.
At least, smoke tests pass... ¯\\\_(ツ)\_/¯

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14208

2022-05-02 20:25 UTC, jeffgdotorg requested changes
Makes sense to me apart from the one missing copyright bump I requested.

2022-05-02 20:25 UTC, jeffgdotorg commented on features/remote-poller/src/main/groovy/org/opennms/groovy/poller/remote/ScanGui.groovy
> +    def m_applications = new HashMap<String, Set<String>>()
Please bump copyright date in this file

2022-05-03 19:24 UTC, cgorantla approved these changes
LGTM!

2022-05-04 13:20 UTC, christianpape approved these changes
LGTM.

2022-05-04 13:35 UTC, jeffgdotorg approved these changes
Looks good, thanks for updating that one copyright date.

2022-05-04 13:41 UTC, merged