NMS-14249: Allow other Oids for BgpSessionMonitor
OpenNMS/opennms pull request #4642
Opened 2022-05-04 09:55 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-14249

2022-05-04 11:55 UTC, fooker requested changes

2022-05-04 11:55 UTC, fooker commented on features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitor.java
> +    class BgpOids {
can be `private static`?

2022-05-04 11:55 UTC, fooker commented on features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitor.java
> +    }
inline this constructor call

2022-05-04 12:25 UTC, christianpape commented on features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitor.java
> +    class BgpOids {
done, but static only due to tests.

2022-05-04 12:25 UTC, christianpape commented on features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitor.java
> +    }
done.

2022-05-04 13:18 UTC, fooker approved these changes

2022-05-05 14:35 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/BgpSessionMonitor.adoc
> +| OID suffix for the table that represents the BGP-peer states
```suggestion
| OID suffix for the table that represents the BGP-peer states.

```

2022-05-05 14:36 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/BgpSessionMonitor.adoc
> +| OID suffix for the table that represents the BGP-peer remote AS number
```suggestion
| OID suffix for the table that represents the BGP-peer remote AS number.

```

2022-05-05 14:36 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/BgpSessionMonitor.adoc
> +| OID suffix for the table that represents the BGP-peer last error code
```suggestion
| OID suffix for the table that represents the BGP-peer last error code.

```

2022-05-05 14:36 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/BgpSessionMonitor.adoc
> +| OID suffix for the table that represents the BGP-peer established time
```suggestion
| OID suffix for the table that represents the BGP-peer established time.

```

2022-05-10 11:26 UTC, fooker approved these changes

2022-05-10 13:58 UTC, merged

2022-05-10 13:58 UTC, Bonrob2 approved these changes
docs look good.