NMS-14182: more alarmd doc tweaks
OpenNMS/opennms pull request #4648
Opened 2022-05-04 18:06 UTC by mmahacek

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14182

2022-05-04 18:14 UTC, mmahacek commented
Extension of items missed in https://github.com/OpenNMS/opennms/pull/4557

2022-05-04 18:35 UTC, Bonrob2 requested changes
minor changes. Thanks!

2022-05-04 18:35 UTC, Bonrob2 commented on docs/modules/operation/pages/alarms/configuring-alarms.adoc
> +Decreasing the significance of the reduction-key is a way to aggregate, for example, all nodes down in to a single alarm.
```suggestion
Decreasing the significance of the reduction-key is a way to aggregate, for example, all nodes into a single alarm.
```

2022-05-04 18:35 UTC, Bonrob2 commented on docs/modules/operation/pages/alarms/configuring-alarms.adoc
> +* alarm-type="3" (notification alarm... alarm with no resolution such as SNMP Authentication Failures)
```suggestion
* alarm-type="3" (notification alarm ... alarm with no resolution, such as SNMP authentication failures)
```

2022-05-04 18:35 UTC, Bonrob2 commented on docs/modules/operation/pages/alarms/configuring-alarms.adoc
> +.Example of a `interfaceUp` event clearing a `interfaceDown` alarm
```suggestion
.Example of an `interfaceUp` event clearing an `interfaceDown` alarm
```

2022-05-04 18:35 UTC, Bonrob2 commented on docs/modules/operation/pages/alarms/configuring-alarms.adoc
> +<1> The `interfaceDown` event sets a `reduction-key` that include enough info to identify a specific interface on a specific node.
```suggestion
<1> The `interfaceDown` event sets a `reduction-key` that includes enough information to identify a specific interface on a specific node.
```

2022-05-05 15:21 UTC, Bonrob2 approved these changes
LGTM!

2022-05-05 15:22 UTC, merged