rebased on top of release-30.x
OpenNMS/opennms pull request #4751
Opened 2022-05-26 13:37 UTC by chuklov

FileEditor automation test that tests regular and wrong behaviour of the user. 

[* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}](https://issues.opennms.org/browse/NMS-14267)

2022-05-26 13:59 UTC, synqotik requested changes
Looks good! Just a few comments to address.

2022-05-26 13:59 UTC, synqotik commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +package org.opennms.smoketest.rest;
Need license header, can copy from another file. May sure to update copyright date to `1999-2022`

2022-05-26 13:59 UTC, synqotik commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +    public void wrongFileName() {
May want a more specific method name (and log message and comment), for example `unsupportedFileExtension`, comment: "Test that the File Editor will deny a file with an unsupported file extension".

2022-05-26 13:59 UTC, synqotik commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +    public void wrongUpdate() {
May want a more specific method name / comment, for example `updateFailsOnXmlValidation`, "Test that the File Editor will deny changes when invalid XML is uploaded for an XML file"

2022-05-26 15:35 UTC, synqotik submitted a review, later dismissed
LGTM!

2022-05-26 15:49 UTC, cgorantla commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +            LOG.error(e.toString());
Add more context to all the  LOG

2022-05-26 15:57 UTC, cgorantla commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +    protected Integer doRequest(final HttpRequestBase request) throws IOException, InterruptedException {
Now that you got that working without `AbstractOpenNMSSeleniumHelper`. Can you try to reuse those methods from `AbstractOpenNMSSeleniumHelper` by making them public static or by Abstracting them in another class

2022-05-26 22:23 UTC, chuklov commented on smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
> +        Thread.sleep(5000);
Unfortunately yes, as if there is no sleep, the test failed as the user is not yet available.

2022-05-31 14:53 UTC, cgorantla approved these changes
LGTM!

2022-05-31 18:49 UTC, merged