NMS-14301: Configure port for juniper devices
OpenNMS/opennms pull request #4762
Opened 2022-05-27 21:13 UTC by cgorantla

Add missing docs

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14301

2022-05-30 05:57 UTC, christianpape approved these changes
LGTM.

2022-05-30 15:09 UTC, Bonrob2 requested changes
a few changes to the docs. thanks!

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +protocol. To achieve this, a TFTP server needs to be started on the OpenNMS instance or on a minion. Normally
```suggestion

To achieve this, a TFTP server needs to be started on the OpenNMS instance or on a Minion. 
```
Separate lines

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +== Backup device configuration on demand
```suggestion
== Back up device configuration on demand
```

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +You can manually backup devices from OpenNMS UI under Info>Device Configs.
```suggestion
You can manually back up devices from the OpenNMS UI under *Info>Device Configs*.
```

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +You can also use the Rest API to trigger device configuration retrieval outside of a monitor schedule.
```suggestion
You can also use the REST API to trigger device configuration retrieval outside of a monitor schedule.
```

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/dcb-requisition.adoc
> +.. `dcb:retention-period`: an optional Java `Period` expression to specify the length of time before "stale" configuration data is deleted from the database (default is `P1Y`, one year)
```suggestion
.. `dcb:retention-period`: an optional Java period expression to specify the length of time before "stale" configuration data is deleted from the database (default is `P1Y`, one year).
```

2022-05-30 15:09 UTC, Bonrob2 commented on docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
> +  Overwrite in metadata as `dcb:schedule`
```suggestion
  Overwrite in metadata as `dcb:schedule`.
```

2022-05-31 20:08 UTC, cgorantla commented
Thanks @Bonrob2 for the review. Updated!

2022-05-31 21:07 UTC, Bonrob2 approved these changes
docs LGTM!

2022-05-31 21:56 UTC, merged