NMS-14154: Add OIA doc
OpenNMS/opennms pull request #4809
Opened 2022-06-02 20:24 UTC by cgorantla

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14154

2022-06-02 20:25 UTC, cgorantla commented on docs/modules/development/pages/oia/introduction.adoc
> +mvn archetype:generate -B -DarchetypeGroupId=org.opennms.integration.api -DarchetypeArtifactId=example-kar-plugin -DarchetypeVersion=1.0.0-SNAPSHOT -DgroupId=com.company -DartifactId=myplugin -Dversi
May have to update `archetypeVersion` once  OIA gets released

2022-06-02 20:35 UTC, Bonrob2 requested changes

2022-06-02 20:35 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +Create a new plugin project using below maven command :
Create a new plugin project using the following Maven command:

2022-06-02 20:35 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +NOTE: You can replace name `myplugin` and package name `com.company.myplugin` and version with your own choices. Generated plugin adds some Java files and feature definitions which are only added as
NOTE: You can replace name `myplugin`, package name `com.company.myplugin`, and version with your own choices. 
Generated plugin adds some Java files and feature definitions which are only added as samples. 
You can update and delete them when needed.

2022-06-02 20:35 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +This plugin generates the following folder structure :
This plugin generates the following folder structure:

2022-06-02 20:35 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +<4> plugin code that depends on OIA code.
<4>Plugin code that depends on OIA code.

2022-06-02 20:41 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +== Start and build a new project with OIA
Start to build a new project with OIA

2022-06-02 20:51 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +== Start and build a new project with OIA
@cgorantla could you add this one as well. Everything else looks good.

2022-06-03 14:59 UTC, cgorantla commented
@Bonrob2 Thanks for the review. I took care of all of suggested changes.

2022-06-06 15:19 UTC, Bonrob2 approved these changes

2022-06-06 15:19 UTC, Bonrob2 commented on docs/modules/development/pages/oia/introduction.adoc
> +== Start and build a new project with OIA
I think I understand why this was changed back to "start and build".

2022-06-06 15:27 UTC, merged