Update perf-data.adoc
OpenNMS/opennms pull request #4848
Opened 2022-06-08 20:35 UTC by mmahacek

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): No JIRA

2022-06-08 20:36 UTC, mmahacek commented
This includes some updates to the perf-data file as well as cross-linking the page in the collection section, since it is related to performance data collection and persisting metrics.

2022-06-08 20:41 UTC, Bonrob2 requested changes
minor change. Thanks!

2022-06-08 20:41 UTC, Bonrob2 commented on docs/modules/operation/pages/events/perf-data.adoc
> +There is also `$\{instance}` variable available that can be used to enrich the resource type's label.
```suggestion
There is also `$\{instance}` variable available that you can use to enrich the resource type's label.
```

2022-06-09 16:56 UTC, Bonrob2 approved these changes
SHIP IT!

2022-06-22 15:21 UTC, mmahacek commented
@freddy61025 Can you verify these changes are still representing accurate information?  Thanks.

2022-07-07 19:17 UTC, merged