NMS-14243: Fixed Heatmap
OpenNMS/opennms pull request #4853
Opened 2022-06-10 07:31 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-14243

2022-06-10 13:17 UTC, amay94 submitted a review, later dismissed
looks good to me

2022-06-10 16:41 UTC, RangerRick requested changes
Looks OK, but can we make sure only `release-30.x` is affected before merging? The security fixes that broke it go all the way back to Meridian 2019 so it seems like this should be fixed in at least `foundation-2022` if not older, assuming it applies to them...

2022-06-11 09:53 UTC, christianpape commented
> Looks OK, but can we make sure only `release-30.x` is affected before merging? The security fixes that broke it go all the way back to Meridian 2019 so it seems like this should be fixed in at least `foundation-2022` if not older, assuming it applies to them...

You're right. Rebased to foundation-2019.

2022-06-13 13:33 UTC, RangerRick approved these changes

2022-06-14 07:48 UTC, merged