Set always ifindex for enlinkd links
OpenNMS/opennms pull request #4909
Opened 2022-06-20 21:33 UTC by rssntn67

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13943

2022-06-21 04:48 UTC, rssntn67 commented
I have reviews the code to certify ifIndex is always set.
The only problem was with LLDP and I provided a method to get the ifindex so that is persisted in lldplink.
Once persisted it is automatically shown in topology.

2022-06-21 12:09 UTC, christianpape requested changes
Only minor changes needed

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpLinkDaoHibernate.java
> +                nodeId,now);
```suggestion
                nodeId, now);
```

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpLinkDaoHibernate.java
> +        ifaces = getHibernateTemplate().find("SELECT ipIf From OnmsIpInterface AS ipIf where ipIf.node.id = ? and ipIf.ipAddress = ?", nodeid,portId);
```suggestion
        ifaces = getHibernateTemplate().find("SELECT ipIf FROM OnmsIpInterface AS ipIf WHERE ipIf.node.id = ? AND ipIf.ipAddress = ?", nodeid, portId);
```

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpLinkDaoHibernate.java
> +            sql.append("where lldplink.id = ").append(linkIds.get(0)).append(" ");
```suggestion
            sql.append("WHERE lldplink.id = ").append(linkIds.get(0)).append(" ");
```

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/LldpTopologyServiceImpl.java
> +            link.setLldpPortIfindex(m_lldpLinkDao.getIfIndex(nodeId,link.getLldpPortId()));
```suggestion
            link.setLldpPortIfindex(m_lldpLinkDao.getIfIndex(nodeId, link.getLldpPortId()));
```

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java
> +        System.err.println("OnmsTopologyVertex: toolTipText:"+vertex.getToolTipText());
```suggestion
        System.err.println("OnmsTopologyVertex: id:" + vertex.getId());
        System.err.println("OnmsTopologyVertex: nodeid:" + vertex.getNodeid());
        System.err.println("OnmsTopologyVertex: label:" + vertex.getLabel());
        System.err.println("OnmsTopologyVertex: address:" + vertex.getAddress());
        System.err.println("OnmsTopologyVertex: iconKey:" + vertex.getIconKey());
        System.err.println("OnmsTopologyVertex: toolTipText:" + vertex.getToolTipText());
```

2022-06-21 12:09 UTC, christianpape commented on features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java
> +
remove empty lines?

2022-06-22 05:15 UTC, christianpape approved these changes
LGTM.

2022-06-22 05:20 UTC, merged