NMS-14120: DCB: Add full script output option to karaf shell command
OpenNMS/opennms pull request #4933
Opened 2022-06-24 19:01 UTC by amay94

This adds a new option (-v, --verbose) to the `dcb-trigger` karaf shell command. If the script starts executing at all during the retrieval, this captures the ssh session I/O and sends it to stdout. 

The dummy script below:

![image](https://user-images.githubusercontent.com/93448083/175648515-221a52ff-aace-422b-b015-b6d44b3f35b2.png)

Results in something like this being seen from the karaf shell:

![image](https://user-images.githubusercontent.com/93448083/175648328-c2026230-619d-44d0-b547-725b9dd453cc.png)

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14120

2022-06-29 16:26 UTC, cgorantla submitted a review, later dismissed
LGTM!

2022-07-01 06:15 UTC, christianpape approved these changes
LGTM.

2022-07-01 07:38 UTC, fooker requested changes

2022-07-01 07:38 UTC, fooker commented on features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DcbTriggerCommand.java
> +                        System.out.println("\nFailed to trigger device config backup: " + response.getErrorMessage());
```suggestion
                        System.err.println("Failed to trigger device config backup: " + response.getErrorMessage());
```

2022-07-01 07:38 UTC, fooker commented on features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
> +    private String dcbScriptDebugOutput;
Can we make this part of the `DeviceConfig` class? This would prevent cluttering this API even more.

2022-07-11 12:42 UTC, christianpape approved these changes
LGTM.

2022-07-11 13:29 UTC, fooker approved these changes

2022-07-11 15:33 UTC, merged