NMS-14436 Enlinkd Clean Adapter Classes
OpenNMS/opennms pull request #4940
Opened 2022-06-27 16:33 UTC by rssntn67

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14436

These changes are anly syntctic changes.
They have been done for next steps in which the code will be improved.

2022-06-29 15:16 UTC, rssntn67 commented
Please take a look at the changes. 
In particular you should check synchronization statement I changed.

2022-07-01 06:24 UTC, christianpape requested changes
Only very small fixes needed.

2022-07-01 06:24 UTC, christianpape commented on features/enlinkd/adapters/common/src/main/java/org/opennms/netmgt/enlinkd/common/TopologyUpdater.java
> +    private final Object m_lock= new Object();
```suggestion
    private final Object m_lock = new Object();
```

2022-07-01 06:24 UTC, christianpape commented on features/enlinkd/daemon/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
> +import org.opennms.netmgt.enlinkd.common.*;
Please use single import statements.

2022-07-01 06:24 UTC, christianpape commented on features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/BridgeTopologyServiceImpl.java
> +    private final Map<Integer, Set<BridgeForwardingTableEntry>> m_nodetoBroadcastDomainMap= new HashMap<>();
```suggestion
    private final Map<Integer, Set<BridgeForwardingTableEntry>> m_nodetoBroadcastDomainMap = new HashMap<>();
```

2022-07-04 17:28 UTC, christianpape approved these changes

2022-07-04 17:31 UTC, merged