NMS-14279: Handle unknown flow direction
OpenNMS/opennms pull request #4969
Opened 2022-07-01 13:26 UTC by fooker

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14279

2022-07-01 15:39 UTC, j-white commented
Should we update flow thresholding here too? Had a patch for that here: https://github.com/OpenNMS/opennms/commit/1934bae9a0fd170bf5f09f6692f3b30cd9ffa9b2#diff-bacdc74287e5ac0fab0facb94ea6430af784e51621d2e145c1c7aca5283ed83dR361

2022-07-03 23:47 UTC, Naicisum commented
@j-white / @fooker - Is there an associated PR for Nephron? 😁

2022-07-04 19:00 UTC, fooker commented
> @j-white / @fooker - Is there an associated PR for Nephron? grin

Not for now. There is https://issues.opennms.org/browse/NMS-14477 to track that.

2022-07-04 19:33 UTC, j-white approved these changes

2022-07-05 10:34 UTC, christianpape requested changes
Minimal changes...

2022-07-05 14:59 UTC, j-white commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +import org.postgresql.shaded.com.ongres.scram.common.bouncycastle.pbkdf2.Integers;
Bad import?

2022-07-05 15:01 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +import org.postgresql.shaded.com.ongres.scram.common.bouncycastle.pbkdf2.Integers;
Ooops

2022-07-05 15:33 UTC, j-white approved these changes

2022-07-05 17:40 UTC, merged