NMS-14352: Update terminology
OpenNMS/opennms pull request #5006
Opened 2022-07-07 16:25 UTC by emarsh1995

- Changed "surveillance category/categories" to "node tag/tags."
- Changed "node categories" to "node tags."
- Updated formatting.

Note: I couldn't find any instances of "provisioning group" or "node category" (singular) in the documentation, so those items haven't been changed.

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14352

2022-07-07 16:48 UTC, mmahacek commented on docs/modules/operation/pages/admin/webui/dashboard.adoc
> +It is specified in the event configuration file in `<logmsg />`
```suggestion
6. Log Msg: The log message from the event definition.
```

2022-07-07 16:48 UTC, mmahacek commented on docs/modules/operation/pages/database-reports/database.adoc
> +|Summary of statistics on outages and availability for user-specified node tag during a user-specified number of days.
```suggestion
| Summary of statistics on outages and availability for user-specified node tag during a user-specified number of days.
```

2022-07-07 16:48 UTC, mmahacek commented on docs/modules/operation/pages/database-reports/database.adoc
> +| Summary of response times across node tag.
```suggestion
| Summary of response times for nodes with a given tag.
```

2022-07-07 16:48 UTC, mmahacek commented on docs/modules/operation/pages/database-reports/database.adoc
> +One does not have to use the data source, though.
Is this sentence necessary?

2022-07-07 16:48 UTC, mmahacek commented on docs/modules/operation/pages/database-reports/templates/avail-summary.adoc
> +Each node tag includes a table of average, minimum, and maximum values for the following availability data for the specified node tag over the specified date range:
```suggestion
For each node tag, the report includes a table of average, minimum, and maximum values for the following availability data over the specified date range:
```

2022-07-07 17:07 UTC, Bonrob2 requested changes
Looking good. Some changes.

2022-07-07 18:17 UTC, Bonrob2 commented on docs/modules/operation/pages/database-reports/database.adoc
> +One does not have to use the data source, though.
Agreed, let's remove it.

2022-07-07 18:19 UTC, emarsh1995 commented on docs/modules/operation/pages/database-reports/database.adoc
> +One does not have to use the data source, though.
```suggestion

```

2022-07-07 18:20 UTC, emarsh1995 commented on docs/modules/operation/pages/database-reports/templates/avail-summary.adoc
> +* Percent availability (per unit in category).
I believe it should be; I'll update this.

2022-07-07 18:21 UTC, emarsh1995 commented on docs/modules/operation/pages/database-reports/templates/avail-summary.adoc
> +* Percent availability (per unit in category).
```suggestion
* Percent outage (per unit in tag).
* Percent availability (per unit in tag).
```

2022-07-07 18:21 UTC, emarsh1995 commented on docs/modules/operation/pages/database-reports/templates/availability.adoc
> +* Percent availability (per node in category).
```suggestion
* Percent outage (per node in tag).
* Percent availability (per node in tag).
```

2022-07-07 18:38 UTC, Bonrob2 commented on docs/modules/operation/pages/admin/webui/dashboard.adoc
> +2. Current Outages: Number of services on the node with outages and total number of monitored services, e.g. with the natural meaning of "3 of 3 services are affected."
Looking at the sample graphic now, I think it's just a way to explain the absence of nouns in what is displayed. I think the phrase confuses things, so suggest the following:

```suggestion
2. Current Outages: Number of services on the node with outages out of the total number of monitored services; for example, "3 of 3 services are affected".
```

2022-07-07 20:38 UTC, emarsh1995 commented on docs/modules/operation/pages/admin/webui/dashboard.adoc
> +1. Node: Label of the monitored node the notification is associated with.
I'd lean towards "monitored" being implied. @mmahacek, do you think we can just say "node" here?

2022-07-07 21:39 UTC, mmahacek commented on docs/modules/operation/pages/admin/webui/dashboard.adoc
> +1. Node: Label of the monitored node the notification is associated with.
Totally.

2022-07-12 14:54 UTC, Bonrob2 reviewed
LGTM!

2022-07-12 14:55 UTC, Bonrob2 approved these changes
In previous comment, I clicked before I approved. :-)

2022-07-12 17:55 UTC, mmahacek approved these changes
No complaints here!

2022-07-12 17:56 UTC, emarsh1995 commented on docs/modules/operation/pages/admin/webui/dashboard.adoc
>  This viewer filters nodes based on the Surveillance View context and shows one graph report at a time.
Cool - I think what we have should cover this. What do you think, @Bonrob2? :)

2022-07-12 17:59 UTC, merged