NMS-14233: Added provisiond config data to datachoice telemetry
OpenNMS/opennms pull request #5019
Opened 2022-07-11 09:08 UTC by christianpape

JIRA: https://issues.opennms.org/browse/NMS-14233

2022-07-11 13:22 UTC, j-white commented on features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
> +        this.m_rescanThreadPoolSize = rescanThreadPoolSize;
this.m_

2022-07-11 13:35 UTC, fooker requested changes

2022-07-11 17:20 UTC, fooker submitted a review, later dismissed

2022-07-12 09:49 UTC, fooker approved these changes

2022-07-12 12:55 UTC, merged