NMS-14453: JdbcQueryDetector documentation
OpenNMS/opennms pull request #5037
Opened 2022-07-13 15:50 UTC by emarsh1995

- Added ./reference/provisioning/detectors/JdbcQueryDetector.adoc. 
- Updated ./reference/nav.adoc.

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue

Don't worry if this sounds like a lot, we can help you get things set up properly.
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14453

2022-07-13 17:07 UTC, Bonrob2 requested changes
A couple of minor changes. Thanks!

2022-07-13 17:33 UTC, emarsh1995 commented on docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
> +Since {page-component-title} uses a PostgreSQL database, the PostgreSQL JDBC driver is included out of the box.
Since this is the same verbiage as in the other JCDB detector pages, do we want to change this around?

2022-07-13 17:36 UTC, mmahacek reviewed
Looking at the source code, a few things popped out at me.

2022-07-13 17:36 UTC, mmahacek commented on docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
> +If the result is `false`, it returns the `not detected` value.
```suggestion
If the query returns a result, the detector returns the `detected` value.
If the query does not return a result, the detector returns the `not detected` value.
```

2022-07-14 19:47 UTC, Bonrob2 commented on docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
> +Since {page-component-title} uses a PostgreSQL database, the PostgreSQL JDBC driver is included out of the box.
We probably should. The "since" guideline from the style guide was fresh in my mind, so we shouldn't use "since" in this context.

2022-07-14 20:02 UTC, mmahacek commented on docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
> +Since {page-component-title} uses a PostgreSQL database, the PostgreSQL JDBC driver is included out of the box.
```suggestion
The PostgreSQL JDBC driver is included out of the box.
```

2022-07-15 18:40 UTC, emarsh1995 commented on docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
> +Since {page-component-title} uses a PostgreSQL database, the PostgreSQL JDBC driver is included out of the box.
I'll go through the other JDBC documents and update this as well, so those will be added in my next commit.

2022-07-15 19:56 UTC, mmahacek approved these changes
LGTM

2022-07-15 20:07 UTC, Bonrob2 approved these changes
LGTM!

2022-07-15 20:08 UTC, merged