NMS-14537: Add option to disable IO collection
OpenNMS/opennms pull request #5042
Opened 2022-07-14 19:18 UTC by amay94

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14537

2022-07-14 20:06 UTC, Bonrob2 requested changes
Minor changes to the docs.

2022-07-14 20:06 UTC, Bonrob2 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +NOTE: Above karaf commands won't persist config by default, use -p option to persist config in {page-component-title} Database.
```suggestion
NOTE: The previous Karaf commands will not persist configuration by default.
Use the -p option to persist configuration in the {page-component-title} database.
```

2022-07-15 12:09 UTC, amay94 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +To disable this, you can configure the scripting service on both Horizon and Minion as below:
You need to disable it on all minions, updated.

2022-07-15 12:10 UTC, amay94 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +By default, the ssh scripting service collects all ssh session output for debugging purposes and saves it in the poller's status.
It's stored in the poller's status so the karaf shell has access to it and can print it if needed. But everything that has access to the poller's status has access to it as well.

2022-07-15 12:11 UTC, amay94 commented on docs/modules/operation/pages/device-config-backup/configuration.adoc
> +By default, the ssh scripting service collects all ssh session output for debugging purposes and saves it in the poller's status.
I changed 'saves' to 'stores', as 'save' could imply persisting in a database.

2022-07-15 20:15 UTC, merged