NMS-14429: Handling flow applications without traffic
OpenNMS/opennms pull request #5045
Opened 2022-07-15 07:11 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-14429

2022-07-18 18:44 UTC, RangerRick approved these changes
Haven't tried the code, but looks reasonable with a scan-through

2022-07-19 12:24 UTC, fooker requested changes

2022-07-19 12:24 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +                        entry.getValue().applications.get(indexKey).entrySet().removeIf(e -> !applicationsToPersist.contains(e.getKey()));
`retainAll` instead of `removeIf`?

2022-07-19 12:24 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +                synchronized (this.applications) {
This really needs synchronisation. But a RWLock is better suited. And the writing part is missing locking.

2022-07-20 09:53 UTC, christianpape commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +                session.dirty = false;
done

2022-07-20 09:53 UTC, christianpape commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +    public void classificationRulesReloaded() {
done

2022-07-20 10:45 UTC, christianpape commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +            }
done

2022-07-20 10:45 UTC, christianpape commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> +                        entry.getValue().applications.get(indexKey).entrySet().removeIf(e -> !applicationsToPersist.contains(e.getKey()));
done

2022-07-21 14:19 UTC, fooker approved these changes

2022-07-21 14:19 UTC, fooker commented on features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
> -                                                                                                      collectionAgent.getHostAddress(),
Do not always reformat.

2022-07-21 16:24 UTC, merged