NMS-14645: Avoid locking thresholding during changes
OpenNMS/opennms pull request #5209
Opened 2022-08-23 20:08 UTC by fooker

The thresholding engine was blocking whenever the config needed to be
reloaded. This is altered to allow reloading the existing thresholding
sets while processing thresholds concurrently.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14645

2022-08-23 23:53 UTC, j-white reviewed
Looks good - this should do the trick

2022-08-24 06:14 UTC, christianpape commented on features/collection/thresholding/api/src/main/java/org/opennms/netmgt/threshd/api/ThresholdInitializationException.java
> +    public Unchecked uncheched() {
```suggestion
    public Unchecked unchecked() {
```

2022-08-24 06:15 UTC, christianpape commented on features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/DefaultThresholdingSetPersister.java
> +                    throw e.uncheched();
```suggestion
                    throw e.unchecked();
```

2022-08-24 06:16 UTC, christianpape requested changes
Typo

2022-08-24 07:42 UTC, fooker commented
Resolved typo and added a comment on why this hacky exception handling is needed.

2022-08-24 07:51 UTC, christianpape submitted a review, later dismissed
LGTM.

2022-08-24 23:20 UTC, Naicisum approved these changes
Tested on 30.0.1 with load for 18 hours. No thread locking issue has appeared as of yet.

2022-08-25 12:01 UTC, christianpape approved these changes
LGTM.

2022-08-25 12:01 UTC, merged