NSM-14360  Added command to build the cache after adding node through API
OpenNMS/opennms pull request #5249
Opened 2022-09-01 15:40 UTC by chuklov

Update to the test. Added karaf command to sync interface to node cache. 

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14360

2022-09-02 08:47 UTC, christianpape approved these changes
LGTM.

2022-09-02 14:01 UTC, fooker requested changes
@chuklov did you already create an issue to tackle the underlying problem? If yes, please add a comment referencing the issue.

2022-09-02 16:29 UTC, chuklov commented
> @chuklov did you already create an issue to tackle the underlying problem? If yes, please add a comment referencing the issue.
Here is the bug ticket for this.
https://issues.opennms.org/browse/NMS-14720

2022-09-02 18:00 UTC, RangerRick commented on smoke-test/src/test/java/org/opennms/smoketest/flow/BmpIT.java
> +        karafShell.runCommand("opennms:sync-node-cache");
aha! that's a clever way to do this, nice

2022-09-08 13:34 UTC, fooker approved these changes

2022-09-08 13:36 UTC, merged