NMS 14671 Add adoc documentation for partial configuration update
OpenNMS/opennms pull request #5264
Opened 2022-09-08 12:05 UTC by dherdt

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14671

2022-09-08 13:12 UTC, Bonrob2 requested changes
A few changes. Thanks!

2022-09-08 13:12 UTC, Bonrob2 commented on docs/modules/development/pages/rest/config_management.adoc
> +Adds an array element to the configuration part specified by configName, configId and the path to the part in JsonPath format. Returns 404 when the configuration does not exist. Returns 400 When the
```suggestion
Adds an array element to the configuration part specified by `configName`, `configId`, and the path to the part in JSONPath format.
Returns 404 when the configuration does not exist.
Returns 400 when the path parameter has a wrong format, specifies a nonexistent path, or the provided part of the configuration has a wrong format.
```

Same questions as above regarding use of the word "part".

2022-09-08 13:12 UTC, Bonrob2 commented on docs/modules/development/pages/rest/config_management.adoc
> +Updates a part of configuration specified by configName, configId and the path to the part in JsonPath format. Returns 404 when the configuration does not exist. Returns 400 When the path parameter h
```suggestion
Updates a part of the configuration specified by `configName`, `configId`, and the path to the part in JSONPath format.
Returns 404 when the configuration does not exist.
Returns 400 when the path parameter has a wrong format, specifies a nonexistent path, or the provided part of the configuration has a wrong format.
```
Same question about the word "path".

2022-09-08 13:12 UTC, Bonrob2 commented on docs/modules/development/pages/rest/config_management.adoc
> +Updates or inserts a part of configuration specified by configName, configId, path to the parent node in JsonPath format and node name. Returns 404 when the configuration does not exist. Returns 400
```suggestion
Updates or inserts a part of the configuration specified by `configName`, `configId`, and the path to the parent node in JSONPath format with the node name.
Returns 404 when the configuration does not exist.
Returns 400 when the `pathToParent` parameter has a wrong format, specifies a nonexistent path, or the provided part of the configuration has a wrong format.
```
In the first sentence, is the path to the parent node in JSONPath format AND includes the node name? If so, please use my suggestion of "with".

Earlier examples do not specify the `pathToParent` parameter. Is this intentional?

2022-09-08 13:12 UTC, Bonrob2 commented on docs/modules/development/pages/rest/config_management.adoc
> +Deletes a part of the configuration specified by configName, configId and the path to the part in JsonPath format. Returns 404 when the configuration does not exist. Returns 400 When the path paramet
```suggestion
Deletes a part of the configuration specified by `configName`, `configId`, and the path to the part in JSONPath format.
Returns 404 when the configuration does not exist.
Returns 400 when the path parameter has a wrong format, specifies a nonexistent path, or the provided part of the configuration has a wrong format.
```
Same questions as before about the word "part".

2022-09-09 09:28 UTC, dherdt commented on docs/modules/development/pages/rest/config_management.adoc
> +Returns a part of configuration specified by configName, configId and the path to the part in JsonPath format. Returns 404 when the configuration does not exist. Returns 400 When the path parameter h
There are two Versions of PUT: with whole "path" and consisting of "pathToParent" and "nodeName".
1: "$.path.to.somting"
2: "$.path.to" and "somting"
the second version works also when "somting" do not exist in note "to"

2022-09-12 13:23 UTC, Bonrob2 reviewed
I'm still not 100% clear on what the "part" of the configuration indicates and how that "part" is determined. I am guessing that users will understand?

2022-09-13 17:09 UTC, Bonrob2 approved these changes

2022-09-13 21:06 UTC, merged