NMS-14674 Set Up Enlinkd schedule time interval based on protocols
OpenNMS/opennms pull request #5309
Opened 2022-09-22 07:59 UTC by rssntn67

Schedule is performed using protocol rescan interval

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14764

2022-09-22 09:31 UTC, christianpape requested changes
Only a typo.

2022-09-22 09:31 UTC, christianpape commented on docs/modules/operation/pages/deep-dive/topology/enlinkd/introduction.adoc
> +The Enlinkd-Bbridge-Discovery process attempts to discover bridge domain links with the data coming from all collected Bridge Forwarding Tables.
```suggestion
The Enlinkd-Bridge-Discovery process attempts to discover bridge domain links with the data coming from all collected Bridge Forwarding Tables.
```

2022-09-22 10:53 UTC, christianpape approved these changes
LGTM.

2022-09-22 11:38 UTC, aramosvizcarra approved these changes
LGTM!

2022-09-22 12:39 UTC, merged

2022-09-22 13:47 UTC, Bonrob2 commented
No major changes from me, but I would have liked to review the docs before the PR was merged.

2022-09-23 05:18 UTC, rssntn67 commented
> No major changes from me, but I would have liked to review the docs before the PR was merged.

I apologize. I was in a hurry, because I'm committing long term work. I splitted my big one (93 file changed) in small PR so that reviewers will have a better look at the changes...
In any case I'm going to create a new Issue for update enlinkd configuration.
In fact I'm changing the configuration file to use priority execution.

2022-09-23 13:12 UTC, Bonrob2 commented
> I apologize. I was in a hurry, because I'm committing long term work. I splitted my big one (93 file changed) in small PR so that reviewers will have a better look at the changes... In any case I'm going to create a new Issue for update enlinkd configuration. In fact I'm changing the configuration file to use priority execution.

No problem. I totally understand. And it read fine anyway. I might have made a few tweaks, but nothing major. It's great that you took the time to write and update the docs!