NMS-14763 Add Priority Executor Classes
OpenNMS/opennms pull request #5313
Opened 2022-09-22 16:14 UTC by rssntn67

Added classes to manage priority scheduling
 Added LegacyPriorityExecutor that use PriorityQueue
 Added Executable that is a ReadyRunnable class with a priority
 Added Tests

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14763

2022-09-22 21:12 UTC, rssntn67 commented
I created the branch from branch

NMS-14771 | Move Common Adapter Enlinkd classes to Core
-- | --


[NMS-14771](https://issues.opennms.org/browse/NMS-14771)	Move Common Adapter Enlinkd classes to Core

So this PR includes also the changes there. In fact new Classes needs Schedulable.java.

2022-09-25 13:30 UTC, aramosvizcarra submitted a review, later dismissed
LGTM!

2022-09-25 14:24 UTC, christianpape requested changes
Only a header is wrong.

2022-09-25 14:24 UTC, christianpape commented on core/daemon/src/main/java/org/opennms/netmgt/scheduler/Executable.java
> + * OpenNMS(R) is Copyright (C) 1999-2018 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```

2022-09-26 07:35 UTC, christianpape submitted a review, later dismissed
LGTM.

2022-09-26 12:04 UTC, aramosvizcarra approved these changes
LGTM!

2022-09-26 13:04 UTC, merged