NMS-14791 Topology-Map Layer broken
OpenNMS/opennms pull request #5398
Opened 2022-10-18 17:46 UTC by rssntn67

Fixed DefaultVertex in enlinkd topology updaters
    Let IplikeSearchProvider be available for all nodes related namespaces
    Fixed IpLikeHopCriteria getVertices getting vertices from the graph namespace

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14791

2022-10-18 18:06 UTC, aramosvizcarra requested changes
just a couple of formatting changes.

2022-10-18 18:06 UTC, aramosvizcarra commented on features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IpLikeHopCriteria.java
> +		m_graphContainer = Objects.requireNonNull(graphContainer);
```suggestion
	m_graphContainer = Objects.requireNonNull(graphContainer);
```

2022-10-18 18:06 UTC, aramosvizcarra commented on features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IpLikeHopCriteria.java
> +		Objects.requireNonNull(graphContainer.getTopologyServiceClient());
```suggestion
	Objects.requireNonNull(graphContainer.getTopologyServiceClient());
```

2022-10-19 07:32 UTC, christianpape approved these changes
LGTM.

2022-10-19 11:18 UTC, aramosvizcarra approved these changes

2022-10-19 16:07 UTC, merged