NMS-14721: Quick Start: Review entire quick start section when complete
OpenNMS/opennms pull request #5488
Opened 2022-11-09 17:02 UTC by Bonrob2

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14721
* http://issues.opennms.org/browse/NMS-14984
* http://issues.opennms.org/browse/NMS-14985

2022-11-10 17:26 UTC, emarsh1995 requested changes
We're nearly there!

2022-11-10 19:05 UTC, Bonrob2 commented on docs/modules/operation/pages/quick-start/notification-config.adoc
> +Subsequent members will then be notified in five-minute increments, from the top of the list of group members to the bottom.
Hmm. No. Will update and remove. Thanks.

2022-11-10 20:13 UTC, emarsh1995 requested changes
Just a few minor nits. :)

2022-11-10 20:13 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/notifications.adoc
> +.. Select `browser` from the list of commands and make sure that it is on.
```suggestion
.. Select `Browser` from the list of commands and make sure that it is on.
```

2022-11-10 21:36 UTC, emarsh1995 requested changes
A couple more changes, then I think we're good to go!

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/concepts.adoc
>  The default delay is zero seconds; this means all group members are notified at the same time.
```suggestion
The default delay is zero seconds; this means that all group members are notified at the same time.
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/concepts.adoc
> +For example, defining a five minute delay will mean that when a notification is generated the first member of the group will be notified immediately.
```suggestion
For example, defining a five minute delay will mean that when a notification is generated, the first member of the group is notified immediately.
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/concepts.adoc
> +Subsequent members will then be notified in five-minute increments, from the top of the list of group members to the bottom.
```suggestion
Subsequent members are then notified in five-minute increments, from the top of the list of group members to the bottom.
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
> += Notification configuration
```suggestion
= Notification Configuration
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
> +The xref:operation:quick-start/notification-config.adoc[configure notifications] chapter in the Quick Start section includes basic procedures to configure and customize {page-component-title} notific
```suggestion
The xref:operation:quick-start/notification-config.adoc[Configure Notifications] chapter in the Quick Start section includes basic procedures to configure and customize {page-component-title} notifications.
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
> +See xref:operation:deep-dive/service-assurance/path-outages.adoc[use path outages to suppress notifications] for additional information.
```suggestion
See xref:operation:deep-dive/service-assurance/path-outages.adoc[Use Path Outages to Suppress Notifications] for additional information.
```

2022-11-10 21:36 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/notification-config.adoc
> +* xref:operation:deep-dive/notifications/configuration.adoc#path-outage-notification[Configure path outages]
```suggestion
* xref:operation:deep-dive/notifications/configuration.adoc#path-outage-notification[Path outages]
```

2022-11-16 14:00 UTC, mhuot approved these changes
Looks good to me, good work

2022-11-16 14:22 UTC, emarsh1995 requested changes
A couple little nits, mostly just to update based on our discussion about referring to symbols in the UI. :)

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/getting-started.adoc
> +After you start the {page-component-title} core services, access the web application at `\http://core-instance-ip:8980/opennms`.
```suggestion
After you start the {page-component-title} core services, you can access the web application at `\http://core-instance-ip:8980/opennms`.
```

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
> +. Click the *Gear* symbol in the top-right of the screen.
Bringing this in line with our discussion about symbols. :)

```suggestion
. Click the *gear* symbol in the top-right of the screen.
```

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/notification-config.adoc
>  Follow these steps to configure event notifications:
There's another instance of the gear symbol here, at line 29, that I can't get to.

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/notifications.adoc
>  == Enable notifications
Another instance of the gear symbol at line 19.

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/notifications.adoc
>  . Click the *Gear* symbol in the top-right of the screen.
```suggestion
. Click the *gear* symbol in the top-right of the screen.
```

2022-11-16 14:22 UTC, emarsh1995 commented on docs/modules/operation/pages/quick-start/users.adoc
>  . Click the *Gear* symbol at the top-right of the screen.
```suggestion
. Click the *gear* symbol at the top-right of the screen.
```

2022-11-16 14:35 UTC, merged