NMS-15027: Add JSON support to the Kafka producer for flows
OpenNMS/opennms pull request #5497
Opened 2022-11-14 17:25 UTC by j-white

JIRA: https://issues.opennms.org/browse/NMS-15027

Allows JSON encoding to be enabled with:
```
config:edit org.opennms.features.flows.persistence.kafka
config:property-set useJson true
config:update
```

2022-11-14 20:42 UTC, Bonrob2 requested changes
Minor changes in the docs. Thanks!

2022-11-14 20:42 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/flows/setup.adoc
> +Enriched flows are stored in `flowDocuments` topic and the payloads are encoded using link:https://developers.google.com/protocol-buffers/[Google Protocol Buffers (GPB)] by default.
```suggestion
Enriched flows are stored in `flowDocuments` topic and the payloads are encoded using link:https://developers.google.com/protocol-buffers/[Google Protocol Buffers] (GPB) by default.
```

2022-11-14 20:42 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/flows/setup.adoc
> +JSON support can be enabled by setting the `useJson` property to `true`.
```suggestion
To enable JSON support, set the `useJson` property to `true`.
```

2022-11-15 18:13 UTC, emarsh1995 reviewed
I've got nothing to add. Once Bonnie's changes are made, I'll approve the docs. Thanks!

2022-11-15 19:49 UTC, Bonrob2 submitted a review, later dismissed
LGTM!

2022-11-16 22:18 UTC, emarsh1995 submitted a review, later dismissed
Docs LGTM. Thank you!

2022-12-05 21:11 UTC, cgorantla approved these changes
LGTM!

2022-12-06 15:06 UTC, merged