NMS-14845: Fixed Destination Path Wizard
OpenNMS/opennms pull request #5527
Opened 2022-11-22 13:07 UTC by christianpape

* JIRA: https://issues.opennms.org/browse/NMS-14845

2022-11-22 19:46 UTC, RangerRick approved these changes

2022-11-23 09:12 UTC, fooker requested changes

2022-11-23 09:12 UTC, fooker commented on opennms-webapp/src/main/webapp/admin/notification/chooseTargets.jsp
> +            for(Target target : targets) {
```suggestion
            for (Target target : targets) {
```

2022-11-23 10:00 UTC, fooker approved these changes

2022-11-23 10:01 UTC, merged