NMS-15008: Get Minion SNMP community string from SCV
OpenNMS/opennms pull request #5554
Opened 2022-12-01 12:47 UTC by fooker

Depends on https://github.com/OpenNMS/opennms-integration-api/pull/76

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/OIA-52

2022-12-01 14:34 UTC, RangerRick submitted a review, later dismissed
Looks reasonable just make sure the OPA side of this is merged and you relaunch the build so it goes green before we merge this.

2022-12-01 14:39 UTC, synqotik commented on features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/scv/SecureCredentialsVaultImpl.java
> +    public void deteleCredentials(String alias) {
Noticed this typo, `deteleCredentials` -> `deleteCredentials`

2022-12-01 15:10 UTC, aramosvizcarra submitted a review, later dismissed
Looks good to me

2022-12-06 10:12 UTC, christianpape requested changes
Some minor things to do...

2022-12-06 10:12 UTC, christianpape commented on features/scv/scvcli/src/main/java/org/opennms/features/scv/cli/commands/DeleteCommand.java
> + * OpenNMS(R) is Copyright (C) 1999-2017 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```

2022-12-06 10:12 UTC, christianpape commented on features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvDeleteCommand.java
> + * OpenNMS(R) is Copyright (C) 1999-2016 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2022 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```

2022-12-06 10:12 UTC, christianpape commented on features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvDeleteCommand.java
> +    @Argument(index = 0, name = "alias", description = "Alias used to retrieve the credentials.", required = true, multiValued = false)
```suggestion
    @Argument(index = 0, name = "alias", description = "Alias for the credentials to be deleted.", required = true, multiValued = false)
```

2022-12-06 13:30 UTC, christianpape submitted a review, later dismissed
LGTM.

2022-12-13 19:28 UTC, merged