NMS-15040: fix ReST queries for OnmsIpInterface snmpPrimary
OpenNMS/opennms pull request #5671
Opened 2023-01-10 22:20 UTC by amay94

This was done in Horizon 29.0.0, see NMS-13469.

The issue was reported in Meridian 2021, but it also exists in foundation-2020.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13469
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15040
* Original PR: https://github.com/OpenNMS/opennms/pull/3556

2023-01-11 13:31 UTC, christianpape requested changes
Only small changes needed.

2023-01-11 13:31 UTC, christianpape commented on opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
> +import javax.ws.rs.*;
don't use wildcard imports

2023-01-11 13:31 UTC, christianpape commented on opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
> +import org.opennms.netmgt.model.*;
don't use wildcard imports

2023-01-11 13:31 UTC, christianpape commented on opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
> +import javax.ws.rs.*;
don't use wildcard imports

2023-01-11 13:31 UTC, christianpape commented on opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
> +import org.opennms.netmgt.model.OnmsMetaData;
don't use wildcard imports

2023-01-12 15:12 UTC, aramosvizcarra approved these changes
LGTM

2023-01-12 15:28 UTC, merged