NMS-14634: Add alt text to Operation (pt. 3)
OpenNMS/opennms pull request #5717
Opened 2023-01-19 14:55 UTC by emarsh1995

- Update `operation/deep-dive/bsm/business-service-map.adoc`, `/introduction.adoc`, `/map-functions.adoc`, `/operational-status.adoc`, `/reduce-functions.adoc`, `/root-cause-impact-analysis.adoc`
- Update `operation/deep-dive/topology/enlinkd/layer-2/bridge-discovery.adoc`, `/cdp-discovery.adoc`, `/lldp-discovery.adoc`
- Update `operation/deep-dive/topology/enlinkd/layer-3/is-is-discovery.adoc`, `/ospf-discovery.adoc`
- Update `operation/deep-dive/topology/graphml-asset-topology-provider.adoc`, `/topology.adoc`
- Update `operation/deep-dive/database-reports/database.adoc`
- Update `operation/deep-dive/database-reports/templates/avail-summary.adoc`, `/availability.adoc`, `/event.adoc`, `/grafana.adoc`, `/interface-avail.adoc`, `/maintenance-expired.adoc`, `/maintenance-strategy.adoc`, `/response-summary.adoc`, `/response-time.adoc`, `/serial.adoc`, `/snmp.adoc`, `/total-bytes.adoc`, `/traffic-rates.adoc`
- Update `operation/deep-dive/ticketing/introduction.adoc`
- Update `operation/deep-dive/workarounds/snmp.adoc`

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14634

2023-01-19 22:28 UTC, Bonrob2 requested changes
Nice work. A few nits. Thanks!

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/topology/graphml-asset-topology-provider.adoc
> +These nodes are shown in the previous diagram as unallocated nodes.
```suggestion
The previous diagram shows these nodes as unallocated nodes.
```

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/topology/graphml-asset-topology-provider.adoc
> +Uses the default settings if a tag isn't included in the command.^1^
```suggestion
Uses the default settings if a tag is not included in the command.^1^
```

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/topology/graphml-asset-topology-provider.adoc
> +. If you simply type `asset-topology:create`, a default topology is created using `providerId`.
```suggestion
. If you type `asset-topology:create`, a default topology is created using `providerId`.
```

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/topology/topology.adoc
> +For example, a value of `server` will hide all categories starting with "server".
```suggestion
For example, a value of `server` hides all categories starting with "server".
```

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/topology/topology.adoc
> +Each vertex on the topology map is represented by an icon.
```suggestion
An icon represents each vertex on the topology map.
```

2023-01-19 22:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/workarounds/snmp.adoc
> +Only a subset of errors will cause {page-component-title}'s SNMP client to attempt retries, however.
```suggestion
Only a subset of errors will cause {page-component-title}'s SNMP client to attempt retries.
```

2023-01-20 14:40 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/bsm/map-functions.adoc
> +The map function defines how the severity of an edge is used in the parent system's reduce function when the operational status is calculated.
I would assume in this case that it's Horizon/Meridian, but I'll ask around. :)

2023-01-20 15:28 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/bsm/map-functions.adoc
> +The map function defines how the severity of an edge is used in the parent system's reduce function when the operational status is calculated.
I think so too. We can replace XX with {page-component-title}.

2023-01-20 15:28 UTC, Bonrob2 requested changes
Everything looks good, just the outstanding comment about the map function.

2023-01-20 15:32 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/bsm/map-functions.adoc
> +The map function defines how the severity of an edge is used in the parent system's reduce function when the operational status is calculated.
```suggestion
The map function defines how to use the severity of an edge in the parent system's reduce function when {page-component-title} calculates the operational status of the business service.
```

2023-01-20 16:18 UTC, Bonrob2 approved these changes
LGTM! Thanks!

2023-01-24 17:43 UTC, merged