NMS-15336: provide an option to disable kafka offset provider
OpenNMS/opennms pull request #5739
Opened 2023-01-25 22:48 UTC by cgorantla

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15336

2023-01-27 21:31 UTC, RangerRick commented
`release-30.x` is a dead repo, it's unsupported and doesn't auto-merge. is this a one-off for a customer or something?

2023-01-31 15:50 UTC, RangerRick requested changes
talked with @cgorantla out of band and he's going to re-target this to the right branch

once that's done re-request and I'll approve

2023-02-03 14:53 UTC, RangerRick approved these changes

2023-07-11 13:56 UTC, Bonrob2 commented on docs/modules/reference/pages/configuration/tuning-kafka.adoc
> +{page-component-title} Core automatically monitors consumer offsets on Kafka to provide lag related metrics.
```suggestion
{page-component-title} Core automatically monitors consumer offsets on Kafka to provide lag-related metrics.
```

2023-07-11 18:14 UTC, j-white approved these changes

2023-07-11 18:17 UTC, RangerRick approved these changes

2023-07-11 18:31 UTC, Bonrob2 approved these changes
LGTM. Thanks!

2023-07-12 18:05 UTC, merged