NMS-14630: Add alt text to Development
OpenNMS/opennms pull request #5746
Opened 2023-01-27 21:38 UTC by emarsh1995

- Update `development/nav.adoc`
- Update `development/amqp/alarm_northbounder.adoc`, `/event_forwarder.adoc`, `/event_receiver.adoc`
- Update `development/bsm/bsm-development.adoc`
- Update `development/reporting/jasperreport-styleguide.adoc`
- Update `development/rest/acknowledgements.adoc`, `/alarm_history.adoc`, `/alarm_statistics.adoc`, `/alarms.adoc`, `/categories.adoc`, `/classifications.adoc`, `/config_management.adoc`, `/device_config.adoc`, `/discovery.adoc`, `/emailnbi-config.adoc`, `/events.adoc`, `/flows.adoc`, `/foreign_sources.adoc`, `/graph.adoc`, `/groups.adoc`, `/health_rest.adoc`, `/heatmap.adoc`, `/ifservices.adoc`, `/ipinterfaces.adoc`, `/javamail-config.adoc`, `/ksc_reports.adoc`, `/maps.adoc`, `/measurements.adoc`, `/meta-data.adoc`, `/node_links.adoc`, `/nodes.adoc`, `/notifications.adoc`, `/outage_timeline.adoc`, `/outages.adoc`, `/perspectivepoller.adoc`, `/requisitions.adoc`, `/resources.adoc`, `/rest-api.adoc`,` /rtc.adoc`, `/scheduled_outages.adoc`, `/situation-feedback.adoc`, `/snmp_configuration.adoc`, `/snmpinterfaces.adoc`, `/snmpmetadata.adoc`, `/snmptrapnbi-config.adoc`, `/syslognbi-config.adoc`, `/user-defined-links.adoc`, `/users.adoc`
- Update `development/topology/graphml.adoc`

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14630

2023-01-30 17:30 UTC, Bonrob2 requested changes
Some nits. Since we've updated some of the GET/PUT/POST headings, I changed the parenthetical text to lower case where I was able to see it/access it. Could you check that they are all updated? Thanks!

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/alarm_history.adoc
>  == GETs (Reading Data)
```suggestion
== GETs (reading data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/config_management.adoc
>  == DELETEs (Removing Data)
```suggestion
== DELETEs (removing data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/groups.adoc
>  == GETs (Reading Data)
```suggestion
== GETs (reading data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/groups.adoc
>  == PUTs (Modifying Data)
```suggestion
== PUTs (modifying data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/groups.adoc
>  == DELETEs (Removing Data)
```suggestion
== DELETEs (removing data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/javamail-config.adoc
>  == PUTs (Modifying Data)
Since the Development section needs a rework anyway, I'll note this for when we update it. :)

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/nodes.adoc
>  == POSTs (Adding Data)
```suggestion
== POSTs (adding data)
```

2023-01-31 14:30 UTC, emarsh1995 commented on docs/modules/development/pages/rest/users.adoc
>  == GETs (Reading Data)
```suggestion
== GETs (reading data)
```

2023-01-31 20:24 UTC, Bonrob2 approved these changes
LGTM. Thanks for all the updates.

2023-01-31 20:36 UTC, merged