update wording on DCB port config
OpenNMS/opennms pull request #5757
Opened 2023-02-01 01:44 UTC by mmahacek

Feedback on docs that there is some ambiguity if this command is required (it's not)

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* JIRA (Issue Tracker): No Jira

2023-02-01 14:14 UTC, Bonrob2 approved these changes
This might take me a while to review. So many words! (Thanks.)

2023-02-01 15:12 UTC, emarsh1995 approved these changes

2023-02-01 18:57 UTC, mmahacek commented
Got some additional feedback from client services...

2023-02-01 18:59 UTC, Bonrob2 requested changes

2023-02-01 18:59 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/device-config-backup/configuration.adoc
> +<1> If you have set `CAP_NET_BIND_SERVICE` on the service unit, you can set the port to the tftp default of `69` and skip the firewall port redirect steps below.
```suggestion
<1> If you have set `CAP_NET_BIND_SERVICE` on the service unit, you can set the port to the TFTP default of `69` and skip the firewall port redirect steps below.
```

2023-02-03 18:43 UTC, Bonrob2 approved these changes
LGTM!

2023-02-03 18:46 UTC, merged