NMS-15274: Move severities chart
OpenNMS/opennms pull request #5761
Opened 2023-02-01 17:02 UTC by emarsh1995

- Update `operation/deep-dive/alarms/alarm-advanced-search.adoc`
- Update `operation/deep-dive/bsm/business-service-map.adoc`, `/operational-status.adoc`
- Update `operation/deep-dive/events/event-advanced-search.adoc`, `/event-configuration.adoc`
- Update `reference/service-assurance/monitors/VmwareMonitor.adoc`

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the JIRA issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15274

2023-02-01 20:52 UTC, mmahacek reviewed
I like the Advanced Search page updates to use tables.

2023-02-01 20:52 UTC, mmahacek commented on docs/modules/operation/pages/deep-dive/bsm/operational-status.adoc
> +In cases where the operational status changed from `Normal` to a higher severity, a `uei.opennms.org/bsm/serviceProblem` event is generated and is assigned the same severity as the business service.
```suggestion
In cases where the operational status changes severity to a state other than `Normal`, a `uei.opennms.org/bsm/serviceProblem` event is generated and is assigned the same severity as the business service.
```

2023-02-01 20:52 UTC, mmahacek commented on docs/modules/operation/pages/deep-dive/bsm/operational-status.adoc
>  NOTE: Use the `serviceProblem` and `serviceProblemResolved` events for notifications or ticketing integration.
```suggestion
TIP: You can use the `serviceProblem` and `serviceProblemResolved` events for notifications or ticketing integration.
```

2023-02-01 20:52 UTC, mmahacek commented on docs/modules/operation/pages/deep-dive/events/event-configuration.adoc
>  $\{OPENNMS_HOME}/bin/send-event.pl uei.opennms.org/internal/reloadDaemonConfig -p 'daemonName Eventd'
Don't need the `\` in a `[source]` block as it renders there.
```suggestion
$OPENNMS_HOME}/bin/send-event.pl uei.opennms.org/internal/reloadDaemonConfig -p 'daemonName Eventd'
```

2023-02-01 20:52 UTC, mmahacek commented on docs/modules/reference/pages/service-assurance/monitors/VmwareMonitor.adoc
> +== Import hosts
Could reference the `reference:provisioning/handlers/vmware.adoc` section that's dedicated to setting up the VMware import process.  Also, that section needs some updating for the v30+ External Requistions UI.

2023-02-01 22:02 UTC, Bonrob2 requested changes
Looks great. Just a few minor changes in addition to Mark's.

2023-02-02 14:10 UTC, emarsh1995 commented on docs/modules/reference/pages/service-assurance/monitors/VmwareMonitor.adoc
> +* `foreignId` (which contains an internal VMware vCenter Identifier)
```suggestion
* `foreignId` (which contains an internal VMware vCenter Identifier)

For more information, see xref:reference:/provisioning/handlers/vmware.adoc[].
```

2023-02-03 15:06 UTC, Bonrob2 reviewed
LGTM! Thank you!

2023-02-03 15:27 UTC, mmahacek approved these changes

2023-02-03 15:52 UTC, merged