NMS-14966: Add smoke test for dual timeseries writes
OpenNMS/opennms pull request #5811
Opened 2023-02-21 14:17 UTC by amay94

The `inmemory-timeseries-plugin` feature is a repackaged version of this: https://github.com/OpenNMS/opennms-integration-api/tree/master/test-suites/tss-tests. I pulled it into the project so I could install it as a feature for testing.

### External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14966

2023-02-21 22:50 UTC, cgorantla submitted a review, later dismissed
LGTM!

2023-02-22 14:00 UTC, christianpape requested changes

2023-02-22 14:31 UTC, christianpape submitted a review, later dismissed
LGTM.

2023-02-22 14:46 UTC, fooker requested changes
Just a bunch of minor code-style nits.

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java
> +    private boolean matches(final Collection<TagMatcher> matchers, final Metric metric) {
can be static?

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java
> +    private boolean matches(final TagMatcher matcher, final Tag tag) {
can be static?

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java
> +        return data;
Wrap with `Collections.immutableMap`

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java
> +        data = new ConcurrentHashMap<>();
Assign in field decl and drop constructor.

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java
> +    }
Isn't that the save as `getAllMetrics`?

2023-02-22 14:46 UTC, fooker commented on features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/shell/GetMetricsCommand.java
> +                System.out.println(String.format("\t%d:%f", dataPoint.getTime().toEpochMilli(), dataPoint.getValue())));
`System.out.printf` insted?

2023-02-22 19:52 UTC, RangerRick approved these changes
I was going to suggest making a new `features-test.xml` for this rather than sticking the feature in `features.xml` but honestly, it's a lot of work for just a semantic change with no real difference. :D

LGTM

2023-03-08 17:16 UTC, merged