[NMS-15410] replace a reference to a file by its content.
OpenNMS/opennms pull request #5855
Opened 2023-03-02 23:11 UTC by bahka

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15410

### Scope: 

1. Rename the package `opennms-cloud-plugin` to `opennms-plugin-cloud`. 

> You can use `yum` or `apt` to make sure your `opennms-cloud-plugin` package is up to date.

Was:
```
opennms@opennms:~$ apt search opennms-cloud-**plugin**

Sorting... Done
Full Text Search... Done
```

Now:
```
opennms@opennms:~$ apt search opennms-**plugin**-cloud
Sorting... Done
Full Text Search... Done
opennms-plugin-cloud/opennms-31 1.0.6-1 all
  OpenNMS :: Plugins :: Cloud Plugin
```

2. Rephrase the line to avoid repetition between lines 39 and 46
> 39: To ensure that the feature is activated on future service restarts, add the feature to a file in `featuresBoot.d`:
> 46: You must configure your {page-component-title} instance to load the Cloud Services plugin on start, and to direct storage to the cloud service.

since the instruction ` to load the Cloud Services plugin on start` already presented at line 39, I removed it from line 46.

3. `opennms.properties.d/hosted_tsdb.timeseries.properties`  doesn't exist if you work with an OpenNMS docker container where cloud-plugin is copied as .kar file. I replaced the reference by the necessary settings in the config file.

> cp ${OPENNMS_HOME}/etc/examples/opennms.properties.d/hosted_tsdb.timeseries.properties ${OPENNMS_HOME}/etc/opennms.properties.d/timeseries.properties
to
> org.opennms.timeseries.strategy=integration

NOTES:
3.1 if the user installed the plugin package by yum / apt  commands this file `hosted_tsdb.timeseries.properties` will be presented in the examples. Should I mention that fact there?

3.2 original file `hosted_tsdb.timeseries.properties` contains following rows:
```
org.opennms.timeseries.strategy=integration
org.opennms.timeseries.config.buffer_type=OFFHEAP
org.opennms.timeseries.config.writer_threads=16
org.opennms.timeseries.config.buffer_size=131072
org.opennms.timeseries.config.offheap.batch_size=8192
org.opennms.timeseries.config.offheap.path=/tmp
org.opennms.timeseries.config.offheap.max_file_size=-1
``` 

where only the `org.opennms.timeseries.strategy=integration` line is mandatory, other could be skipped or configured in accordance with user needs.

2023-03-02 23:27 UTC, mmahacek commented
Probably should retarget this to `foundation-2023`

Are we going to make reference to the other suggested settings for the plugin that were removed?
```
org.opennms.timeseries.config.buffer_type=OFFHEAP
org.opennms.timeseries.config.writer_threads=16
org.opennms.timeseries.config.buffer_size=131072
org.opennms.timeseries.config.offheap.batch_size=8192
org.opennms.timeseries.config.offheap.path=/tmp
org.opennms.timeseries.config.offheap.max_file_size=-1
```

2023-03-03 00:48 UTC, bahka commented
@mmahacek it was just an example, e2e tests have another settings (https://github.com/OpenNMS-Cloud/TSaaS/blob/main/system-tests/src/main/resources/opennms/opennms.properties.d/timeseries.properties). 

I asked @freddy61025 to be sure do we need highlight them or not.

2023-03-03 01:18 UTC, freddy61025 commented
> https://github.com/OpenNMS-Cloud/TSaaS/blob/main/system-tests/src/main/resources/opennms/opennms.properties.d/timeseries.properties

Those are for enable offheap storage to allow at least six hours outages for TSaaS. (Assume their disk have good IO.)

2023-03-03 02:10 UTC, mmahacek commented
The opennms-cloud organization is private and I don't have access to view that (nor do public users)

2023-03-03 14:04 UTC, Bonrob2 requested changes
Minor change, but the text looks good to me.

2023-03-03 14:04 UTC, Bonrob2 commented on docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
> +You can use `yum` or `apt` to make sure your `opennms-plugin-cloud` package is up-to-date.
```suggestion
You can use `yum` or `apt` to make sure your `opennms-plugin-cloud` package is up to date.
```
This is one of those ones I always have to look up, but in this context, up to date is not hyphenated.

2023-03-03 16:23 UTC, Bonrob2 approved these changes
LGTM!

2023-03-03 16:25 UTC, bahka commented on docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
> +org.opennms.timeseries.strategy=integration
@mmahacek Freddy mentioned that other properties were set for `off-heap storage` feature (https://docs.opennms.com/meridian/2023/deployment/minion/off-heap-storage.html).

2023-03-03 16:43 UTC, bahka commented
@mmahacek the content from TSaaS integration tests (most of them was taken from an opennms default configuration).

strategy was set as ENV variable to match with `integration` and `rrd` (dual writing feature). 
```
org.opennms.timeseries.config.ring_buffer_size=131072
org.opennms.timeseries.config.writer_threads=2

# change aggregation interval from 5m to 10s 
org.opennms.timeseries.query.interval_divider=2
org.opennms.timeseries.query.minimum_step=10000
org.opennms.timeseries.query.heartbeat=150000

cache.timeseriesPersisterMetaTagCache.maximumSize=131072
cache.timeseriesSearcherCache.maximumSize=131072
cache.timeseriesMetaDataCache.maximumSize=131072

org.opennms.newts.query.minimum_step=10000
```

2023-03-03 17:33 UTC, freddy61025 commented
FYI there those options already have docuement.

https://docs.opennms.com/horizon/31/deployment/time-series-storage/timeseries/configuration.html#additional-configuration-options

2023-03-06 20:31 UTC, merged