OIA-55: Implement collector config extensions
OpenNMS/opennms pull request #5874
Opened 2023-03-14 09:08 UTC by fooker

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/OIA-55

2023-03-14 17:25 UTC, RangerRick requested changes
this looks good to me, but it might be nice to see a test to make sure reload behaves properly after things change on both sides (local and OIA configs)

seems like daemon reloads not working right is a regular issue with support stuff, best to have an explicit test

2023-04-06 12:48 UTC, fooker commented
There are forced smoke tests for this: https://app.circleci.com/pipelines/github/OpenNMS/opennms?branch=jira%2FOIA-55-smoke

2023-04-06 12:48 UTC, fooker commented
> this looks good to me, but it might be nice to see a test to make sure reload behaves properly after things change on both sides (local and OIA configs)
> 
> seems like daemon reloads not working right is a regular issue with support stuff, best to have an explicit test

Done.

2023-04-06 12:58 UTC, christianpape approved these changes
LGTM.

2023-04-06 12:58 UTC, christianpape commented on opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdExternalIT.java
> + * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2007-2023 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
```

2023-04-06 14:24 UTC, RangerRick approved these changes

2023-04-06 19:01 UTC, RangerRick approved these changes

2023-04-07 09:10 UTC, merged