NMS-15518: Simplify the installation docs
OpenNMS/opennms pull request #5899
Opened 2023-03-20 20:03 UTC by mfuhrmann

### All Contributors

* [ ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the Jira link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the Jira issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here,
or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15518

2023-03-20 20:11 UTC, mfuhrmann commented
What I've done so far in the `core` section. 

1. Moved to reference section
* receive-snmp-traps
* install-jdbc-driver
* selinux
2. Also added a `related topics` section with those 3 references
3. Applied the encrypted database credentials way and dropped the clear text version. The idea here is to avoid letting people do the clear text way and after they are finished letting them know there is a better way :tada:
4. Renamed the title `Basic Horizon Deployment` to `OpenNMS {page-component-title}`

2023-03-21 21:32 UTC, Bonrob2 reviewed
Just one minor change. I think the restructuring works well. Thank you!

2023-03-21 21:32 UTC, Bonrob2 commented on docs/modules/deployment/pages/core/getting-started.adoc
> +* If in usage: A SELinux policy that permits binding to the ICMP service.
```suggestion
* If in use: A SELinux policy that permits binding to the ICMP service.
```

2023-03-22 14:11 UTC, emarsh1995 requested changes
Some changes for flow and language. Thanks!

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
>  <1> Set the database name {page-component-title} should use.
```suggestion
----
<1> Set the database name that {page-component-title} should use.
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
>  Some system kernels do not honor this setting, and in those cases, additional configuration is required to allow binding to privileged ports.
```suggestion
Some system kernels do not honor this setting; in those cases, additional configuration is required to allow binding to privileged ports.
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
>  We recommend creating a systemd overlay to add the necessary settings to the service configuration.
```suggestion
We recommend creating a systemd overlay to add the necessary settings to the service configuration:
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
>  [source, properties]
```suggestion
+
[source, properties]
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +It is possible to store the PostgreSQL credentials in the secure credentials vault.
```suggestion
You can store your PostgreSQL credentials in the secure credentials vault.
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +To achieve this, use the `scvcli` command line utility to add the credentials, and reference these credentials in `opennms-datasources.xml`.
```suggestion
To do this, use the `scvcli` command line utility to add the credentials, and reference these credentials in `opennms-datasources.xml`:
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +.Create encrypted credentials for PostgreSQL database connections:
```suggestion
. Create encrypted credentials for the PostgreSQL database connections:
+
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
>  ----
```suggestion
. Edit `opennms-datasources.xml` with `vi`:
+
[source, console]
sudo -u opennms vi /opt/opennms/etc/opennms-datasources.xml
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +.Set encrypted credentials to access the PostgreSQL database
```suggestion
. Set encrypted credentials to access the PostgreSQL database:
+
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
>                      database-name="opennms"<1>
```suggestion
                    database-name="opennms" <1>
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +                    password="${scv:postgres:password}" /><3>
```suggestion
                    user-name="${scv:postgres:username}" <2>
                    password="${scv:postgres:password}" /> <3>
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +                    password="${scv:postgres-admin:password}" /><5>
```suggestion
                    user-name="${scv:postgres-admin:username}" <4>
                    password="${scv:postgres-admin:password}" /> <5>
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
>  <1> Set the database name {page-component-title} should use.
```suggestion
----
<1> Set the database name that {page-component-title} should use.
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
>  If you run on an older kernel, and are unable to upgrade your OS, you need to assign CAP_NET_RAW capabilities:
```suggestion
If you run on an older kernel and you cannot upgrade your OS, you need to assign `CAP_NET_RAW` capabilities:
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
> +Run `systemctl edit opennms.service` and add the following line to the `[Service]` section:
```suggestion
. Run `systemctl edit opennms.service` and add the following code to the `[Service]` section:
```

2023-03-22 14:11 UTC, emarsh1995 commented on docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
>  [source, properties]
```suggestion
+
[source, properties]
```

2023-03-22 14:11 UTC, emarsh1995 requested changes
Some changes for flow and language. Thanks!

ETA: GitHub submitted my review twice for some reason; please disregard this one.

2023-03-22 22:14 UTC, mmahacek reviewed
I haven't read too far, and want to see it again after @emarsh1995's suggestions are processed, but I am liking the changes overall.
This is targeting `develop` which won't hit the docs until v32.  As the info does apply to previous versions, this should probably target `foundation-2023` (@Bonrob2 to confirm).

2023-03-22 22:14 UTC, mmahacek commented on docs/modules/reference/pages/configuration/selinux.adoc
> +=== SELinux and ICMP permissions
```suggestion
= SELinux and ICMP permissions
```

2023-03-22 22:14 UTC, mmahacek commented on docs/modules/reference/pages/configuration/receive-snmp-traps.adoc
> +== Receive SNMP traps/informs
```suggestion
= Receive SNMP traps/informs
```

2023-03-29 18:13 UTC, mfuhrmann commented
Closing this one. I pushed the changes into foundation-2023 base here https://github.com/OpenNMS/opennms/pull/5930

2023-03-29 18:13 UTC, closed without merging