NMS-15320: Added docs section for SameSite Cookie Attribute
OpenNMS/opennms pull request #5902
Opened 2023-03-21 10:31 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/NMS-15320

2023-03-21 13:24 UTC, Bonrob2 requested changes
A few minor updates. Thank you!

2023-03-21 13:24 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +The SameSite Cookie Attribute was introduced to control access to cookies and helps to prevent various XSS- and CSRF-attacks.
```suggestion
The SameSite Cookie attribute controls access to cookies and helps prevent various cross-site scripting (XSS) and cross-site request forgery (CSRF) attacks.
```

2023-03-21 13:24 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +== Relaxing the SameSite Attribute enforcement policy
```suggestion
== Relax the SameSite attribute enforcement policy
```

2023-03-21 13:24 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +In order to change the enforcement policy, you need to alter the file `$OPENNMS_HOME/jetty-webapps/opennms/WEB-INF/web.xml`.
```suggestion
To change the enforcement policy, you need to alter the `$OPENNMS_HOME/jetty-webapps/opennms/WEB-INF/web.xml` file.
```

2023-03-21 13:30 UTC, christianpape commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +    <comment>__SAME_SITE_STRICT__</comment> <1>
Yes, the double undescores are needed.

2023-03-21 13:32 UTC, Bonrob2 submitted a review, later dismissed
LGTM! Thank you!

2023-03-22 14:17 UTC, emarsh1995 requested changes

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +OpenNMS ships with the most secure configuration, *strict*, for its session cookie.
```suggestion
{page-component-title} ships with the most secure configuration (`strict`) for its session cookie.
```

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +This means that the session cookie will not be sent for any cross-site request.
```suggestion
This means that the session cookie will not be sent for any cross-site requests.
```

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +There may be environments where a user wants to relax this enforcement by setting the SameSite attribute to *lax*.
```suggestion
There may be environments where a user wants to relax this enforcement by setting the SameSite attribute to `lax`.
```

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +== Relax the SameSite attribute enforcement policy
```suggestion
== Relax enforcement policy
```

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +To change the enforcement policy, you need to alter the `$OPENNMS_HOME/jetty-webapps/opennms/WEB-INF/web.xml` file.
```suggestion
To change the enforcement policy, you must alter `$OPENNMS_HOME/jetty-webapps/opennms/WEB-INF/web.xml`:
```

2023-03-22 14:17 UTC, emarsh1995 commented on docs/modules/operation/pages/deep-dive/admin/configuration/same-site-cookie.adoc
> +
```suggestion
+
```

2023-03-23 13:10 UTC, emarsh1995 requested changes
One minor change; otherwise, LGTM. :)

2023-03-23 13:45 UTC, Bonrob2 approved these changes
LGTM!

2023-03-28 06:29 UTC, merged