NMS-15514: Upgrade to Newts 3.0.0
OpenNMS/opennms pull request #5939
Opened 2023-03-31 18:43 UTC by j-white

JIRA: https://opennms.atlassian.net/browse/NMS-15514

2023-03-31 18:46 UTC, j-white commented on container/features/pom.xml
> +  <repositories>
Will remove once we cut a release of Newts 3.0.0

2023-03-31 18:46 UTC, j-white commented on dependencies/cassandra-test/pom.xml
> +  <repositories>
Will remove once we cut a release of Newts 3.0.0

2023-03-31 18:46 UTC, j-white commented on dependencies/newts/pom.xml
> +  <repositories>
Will remove once we cut a release of Newts 3.0.0

2023-03-31 18:46 UTC, j-white commented on features/distributed/kv-store/blob/blob-itests/src/test/java/org/opennms/features/distributed/blob/cassandra/CassandraBlobStoreIT.java
> +    public static NewtsInstance newtsInstance = new NewtsInstance();
This uses TestContainers, which means we now rely on Docker for ITs outside of the `smoke-tests`.

2023-03-31 18:46 UTC, j-white commented on features/newts/src/main/java/org/opennms/netmgt/newts/cli/Init.java
> +        // FIXME: Cleanup
TODO

2023-03-31 18:46 UTC, j-white commented on features/newts/src/main/java/org/opennms/netmgt/newts/support/CassandraPoolConfiguration.java
> +    @Bean(name="cassandra.pool.connections-per-host")
TODO: Document breaking change

2023-04-05 21:23 UTC, RangerRick commented on features/distributed/distributed-cassandra/cassandra-api/src/main/java/org/opennms/features/distributed/cassandra/api/CassandraSession.java
> + * Copyright (C) 2023 The OpenNMS Group, Inc.
2019-2023?

2023-04-06 13:49 UTC, emarsh1995 requested changes
Some updates to the text. Thanks. :)

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/deployment/pages/time-series-storage/newts/configuration.adoc
>  | Name  | Description   | Default
```suggestion
| Name  | Description   | Default Value
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/deployment/pages/time-series-storage/newts/configuration.adoc
>  See http://docs.datastax.com/en/cassandra/2.1/cassandra/dml/dml_config_consistency_c.html[Configuring Data Consistency] in the Cassandra documentation for a list of available options.
```suggestion
See http://docs.datastax.com/en/cassandra/2.1/cassandra/dml/dml_config_consistency_c.html[Configuring Data Consistency] in the official Cassandra documentation for a list of available options.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/deployment/pages/time-series-storage/newts/configuration.adoc
> +| Cassandra driver settings file - overwrites all other driver related settings
```suggestion
| Cassandra driver settings file.
The configuration settings defined in this file overwrite all other driver-related settings.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/deployment/pages/time-series-storage/newts/configuration.adoc
> +See https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/configuration/reference/[Reference configuration] for details.
```suggestion
See https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/configuration/reference/[Reference Configuration] in the official DataStax documentation for details.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +The DataStax driver for Cassandra was updated from version 3.x to 4.x which allowed us to introduce the following functionality:
```suggestion
The DataStax driver for Cassandra was updated from version 3.x to 4.x.
This allows us to introduce the following functionality:
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +See bellow for a list of related breaking changes.
```suggestion
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +
```suggestion
. `org.opennms.newts.config.datacenter` is now required.
Set this to the value of your local datacenter for the best performance.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +Use `org.opennms.newts.config.connections-per-host` instead if you would like to tune the number of connections per host.
```suggestion
. `org.opennms.newts.config.core-connections-per-host` and `org.opennms.newts.config.max-connections-per-host` have been removed.
Use `org.opennms.newts.config.connections-per-host` if you want to configure the number of connections per host.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +Some JMX MBeans have changed object names due to an upgrade of the Dropwizard Metrics library.
```suggestion
Because of an upgrade of the Dropwizard Metrics library, some JMX MBeans object names have changed.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +Built-in data-collection config have been updated to use the new object names and will continue to work as is.
```suggestion
The built-in data collection configurations have been updated to use the new object names, and will continue to work as-is.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +If you have additional collections, or are otherwise relying on the MBeans, you may need to adjust references as well.
```suggestion
If you have other collections, or you are otherwise relying on MBeans, you may need to adjust the object references there.
```

2023-04-06 13:49 UTC, emarsh1995 commented on docs/modules/releasenotes/pages/whatsnew.adoc
> +For example `org.opennms.newts:name=search.update,type=timers` is now refered to as `org.opennms.newts:name=search.update,type=timers`, with the `type` attribute being added.
```suggestion
For example, org.opennms.newts:name=search.update,type=timers` has become `org.opennms.newts:name=search.update,type=timers`, and the `type` attribute has been added to the object.
```

2023-04-06 13:49 UTC, emarsh1995 commented on features/newts/src/main/java/org/opennms/netmgt/newts/cli/Init.java
> +            System.out.printf("Initializing the '%s' keyspace with driver settings pull from: %s%n", keyspace, driverSettingsFile);
```suggestion
            System.out.printf("Initializing the '%s' keyspace with driver settings from: %s%n", keyspace, driverSettingsFile);
```

2023-04-06 17:56 UTC, Bonrob2 reviewed
No additional changes from me.

2023-04-18 16:47 UTC, j-white commented
Updated to released artifacts and addressed all feedback. Should be good to go!

2023-04-18 17:10 UTC, Bonrob2 approved these changes
LGTM! Emily is away for a few days, but I reviewed her comments and everything has been addressed.

2023-04-18 19:58 UTC, RangerRick approved these changes
do eeeet

2023-04-18 20:08 UTC, merged