NMS-8894: Add transient attribute to Measurements API
OpenNMS/opennms pull request #5947
Opened 2023-04-03 15:26 UTC by emarsh1995

- Update `development/rest/measurements.adoc`

### All Contributors

* [x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### Contribution Checklist

* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, please:
  1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the Jira link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
  4. once you've created this PR, please link to it in a comment in the Jira issue
  Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are there unit and/or integration tests?
* If this PR targets a `foundation-*` branch, does it try to avoid changing files in `$OPENNMS_HOME/etc/`?

### What's Next?

A PR should be assigned at least 2 reviewers.  If you know that someone would be a good person to review your code, feel free to add them.

If you need help making additions or changes to the documentation related to your changes, please let us know.

In any case, if anything is unclear or you want help getting your PR ready for merge, please don't hesitate to say something in the comments here, or in [the #opennms-development chat channel](https://chat.opennms.com/opennms/channels/opennms-development).

Once reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the OGP) you are welcome to merge the PR when you're ready. Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-8894

2023-04-03 16:00 UTC, emarsh1995 commented on docs/modules/development/pages/rest/measurements.adoc
> +<2> Indicates that the attribute is needed for query input.
Thanks! I'll update these.

2023-04-03 16:20 UTC, mmahacek commented on docs/modules/development/pages/rest/measurements.adoc
> +<2> Indicates that the attribute is needed for query input.
To be more accurate, the transient settings determine if the attribute is included in the response or not.  It technically doesn't mean if the attribute is needed or not. Any attribute referenced in an expression query must be requested individually.  When setting transient to `true`, it is a way to hide the source attribute in the response so you only get the calculated expression result back.

2023-04-03 17:11 UTC, Bonrob2 requested changes
A few minor changes. Thanks!

2023-04-03 17:11 UTC, Bonrob2 commented on docs/modules/development/pages/rest/measurements.adoc
> +The following example demonstrates how the GET function and its parameters can be used with cURL.
```suggestion
The following example demonstrates how you can use the GET function and its parameters with cURL.
```

2023-04-03 17:11 UTC, Bonrob2 commented on docs/modules/development/pages/rest/measurements.adoc
> +| Index into the samples array that the present calculation is referencing.
```suggestion
| Index into the samples array that the present calculation references.
```

2023-04-03 17:11 UTC, Bonrob2 commented on docs/modules/development/pages/rest/measurements.adoc
> +| Passes a string to the JEXL engine to be evaluated as if it were entered as a normal expression. +
```suggestion
| Passes a string to the JEXL engine to evaluate as if it were entered as a normal expression. +
```

2023-04-05 12:57 UTC, Bonrob2 requested changes
Pedantic feedback. :-)

2023-04-05 13:25 UTC, emarsh1995 commented on docs/modules/development/pages/rest/measurements.adoc
> +When using Newts, you can set the step size arbitrarily; this is because the aggregation is performed at request time.
I would assume this means that you can set the value to an arbitrary number. @mmahacek, could you confirm?

2023-04-10 21:22 UTC, jeffgdotorg submitted a review, later dismissed
Looks good apart from the one suggestion.

2023-04-10 21:22 UTC, jeffgdotorg commented on docs/modules/development/pages/rest/measurements.adoc
> +You can use the Measurements API to retrieve collected values stored in RRD or JRB files, and in Newts.
```suggestion
You can use the Measurements API to retrieve collected values stored in RRD or JRB files, in Newts, and in other supported time-series databases.
```

2023-04-10 21:22 UTC, jeffgdotorg commented on docs/modules/development/pages/rest/measurements.adoc
> +When using Newts, you can set the step size arbitrarily; this is because the aggregation is performed at request time.
I think Emily's read of this is the correct one.

2023-04-11 13:40 UTC, emarsh1995 commented on docs/modules/development/pages/rest/measurements.adoc
> +When using Newts, you can set the step size arbitrarily; this is because the aggregation is performed at request time.
```suggestion
When using Newts, you can set the step size to an arbitrary number; this is because the aggregation is performed at request time.
```

2023-04-11 14:21 UTC, merged