NMS-15609: JDK17 Support
OpenNMS/opennms pull request #6019
Opened 2023-04-20 17:41 UTC by RangerRick

This PR includes a number of updates to support JDK17:

* fix a number of integration tests to properly set `opennms.home` for JDK17's stricter `Paths.get(null)` handling
* handles JDK17's stricter controls on cross-module (and non-module) introspection (`--add-modules=`, `--add-reads=`, `--add-exports=`, and `--add-opens=`)
* bumps a few dependencies that needed to be updated to JDK17-compatible versions
* fixed a few other tests where issues cropped up from changes in type strictness or other small behavior changes

During the development of this branch, it was also temporarily changed to perform a complete build/test/smoke run using only JDK17, so that any JDK17-specific bugs could be squashed.

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15609

2023-04-20 17:51 UTC, j-white commented
Nice! LGTM.

2023-04-20 20:42 UTC, mershad-manesh commented on core/icmp-jna/src/test/java/org/opennms/jicmp/jna/Server.java
Minor item, should the copyright dates say 2023?

2023-04-20 20:43 UTC, mershad-manesh commented on features/topology-map/plugins/org.opennms.features.topology.plugins.topo.asset/src/test/java/org/opennms/features/topology/plugins/topo/asset/filter/FilterParserTest.java
Minor item, should the copyright dates be 2023?

2023-04-21 05:15 UTC, christianpape requested changes
LGTM. Only a few headers need to be changed to 2023.

2023-04-21 05:15 UTC, christianpape commented on core/icmp-jna/src/test/java/org/opennms/jicmp/jna/Server.java
> + * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2011-2023 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
```

2023-04-21 05:15 UTC, christianpape commented on features/topology-map/plugins/org.opennms.features.topology.plugins.topo.asset/src/test/java/org/opennms/features/topology/plugins/topo/asset/filter/FilterParserTest.java
> + * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2017-2023 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
```

2023-04-21 05:15 UTC, christianpape commented on opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/ScriptPolicyTest.java
> + * OpenNMS(R) is Copyright (C) 1999-2022 The OpenNMS Group, Inc.
```suggestion
 * Copyright (C) 2018-2023 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
```

2023-04-24 07:12 UTC, christianpape approved these changes

2023-04-24 14:04 UTC, christianpape submitted a review, later dismissed
LGTM.

2023-04-24 19:17 UTC, j-white commented on core/cli/src/main/resources/bin/_module_opts.sh
> +    "org.apache.karaf.specs/org.apache.karaf.specs.locator=java.xml,ALL-UNNAMED"
This gets output on startup now: `WARNING: Unknown module: org.apache.karaf.specs specified to --add-exports`

2023-05-05 20:18 UTC, mershad-manesh approved these changes
The changes seems ok to me

2023-05-05 20:21 UTC, RangerRick commented
Screw it, let's do this! Better to let any other problems get found in `develop` than languishing in a branch forever.

https://www.youtube.com/watch?v=PHFWpx1Y-_k

2023-05-05 20:21 UTC, merged