NMS-14692: Allow destination paths to be triggered from the shell and UI
OpenNMS/opennms pull request #6045
Opened 2023-04-26 16:52 UTC by j-white

JIRA: https://opennms.atlassian.net/browse/NMS-14692

There's a button now!

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1379749/234647282-b894f4d8-b5f3-4410-bd70-8a24f4ec9c77.png">

2023-05-02 12:00 UTC, christianpape requested changes
Really useful. Code-wise fine for me. It would be nice to have some of this described in the documentation, especially Karaf command and the ReST endpoint.

2023-05-02 14:18 UTC, aramosvizcarra submitted a review, later dismissed
LGTM

2023-05-09 20:13 UTC, Bonrob2 commented
> Really useful. Code-wise fine for me. It would be nice to have some of this described in the documentation, especially Karaf command and the ReST endpoint.

There is some documentation on this, but not the Karaf/REST endpoint: https://docs.opennms.com/horizon/31/operation/quick-start/notifications.html#configure-destination-paths

2023-05-09 20:15 UTC, Bonrob2 reviewed
text LGTM!

2023-05-31 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenNMS/opennms?pullRequest=6045) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenNMS/opennms?pullRequest=6045) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenNMS/opennms?pullRequest=6045) it.</sub>

2023-05-31 16:27 UTC, j-white commented
Added some basic reference documentation.

2023-05-31 17:31 UTC, Bonrob2 requested changes
A few minor changes to the docs.

2023-05-31 17:31 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/notifications/shell.adoc
> +The following shell commands are made available to help administer and debug Notifd.
```suggestion
The following shell commands can help you to administer and debug Notifd.
```

2023-05-31 17:31 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/notifications/shell.adoc
> +This can be used to verify that commands are properly configured and that notifications get sent to the recipients.
```suggestion
Use to verify that commands are properly configured and that notifications get sent to the recipients.
```

2023-05-31 18:26 UTC, j-white commented
Should be all set now :)

2023-05-31 18:27 UTC, Bonrob2 approved these changes
docs LGTM!

2023-06-01 06:17 UTC, christianpape approved these changes
LGTM.

2023-06-01 14:18 UTC, RangerRick commented
I'l go ahead and merge this since @j-white is out until next week

2023-06-01 14:18 UTC, merged