NMS-15693: XML Doc updates
OpenNMS/opennms pull request #6134
Opened 2023-05-19 16:09 UTC by mmahacek

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15693

2023-05-19 17:16 UTC, Bonrob2 requested changes
Minor changes. Thanks!

2023-05-19 17:16 UTC, Bonrob2 commented on docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
> +=== Customizing the source request
```suggestion
=== Customize the source request
```

2023-05-19 17:16 UTC, Bonrob2 commented on docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
> +=== Retrieving data from a POST request
```suggestion
=== Retrieve data from a POST request
```

2023-05-19 17:16 UTC, Bonrob2 commented on docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
> +XML Collections are defined in `$\{OPENNMS_HOME}/etc/xml-datacollection-config.xml` and groups are defined in `$\{OPENNMS_HOME}/etc/xml-datacollection/`.
```suggestion
XML collections are defined in `$\{OPENNMS_HOME}/etc/xml-datacollection-config.xml` and groups are defined in `$\{OPENNMS_HOME}/etc/xml-datacollection/`.
```

2023-05-19 17:23 UTC, Bonrob2 submitted a review, later dismissed
LGTM! Thank you!

2023-05-23 13:27 UTC, Bonrob2 commented on docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
> +| Full path to XSLT file to transform XML data before processing to collection definitions
```suggestion
| Full path to XSLT file to transform XML data before processing to collection definitions.
```

2023-05-23 15:01 UTC, agalue approved these changes
LGTM

2023-05-23 16:54 UTC, Bonrob2 approved these changes
LGTM. Thanks!

2023-05-23 16:59 UTC, merged