NMS-15853: More BMP docs related to distributed processing.
OpenNMS/opennms pull request #6394
Opened 2023-07-18 19:49 UTC by j-white

JIRA: https://opennms.atlassian.net/browse/NMS-15853

2023-07-18 19:50 UTC, j-white commented
@dino2gnt with this and the examples in the BMP playground: https://github.com/opennms-forge/bmp-playground/pull/6, is there anything that needs more clarity?

2023-07-19 14:18 UTC, Bonrob2 requested changes
a few minor changes. Thanks.

2023-07-19 14:18 UTC, Bonrob2 commented on docs/modules/reference/pages/telemetryd/protocols/bmp/bmp.adoc
> +All of the BMP related adapters can be ran on Sentinel, allowing you to generate events, metrics and ingest route changes.
```suggestion
All of the BMP-related adapters can run on Sentinel, allowing you to generate events and metrics, and ingest route changes.
```

2023-07-19 14:18 UTC, Bonrob2 commented on docs/modules/reference/pages/telemetryd/protocols/bmp/bmp.adoc
> +Sentinel can be used to process BMP statistics ingested by one or more Minions in order to alleviate load on the core.
```suggestion
You can use Sentinel to process BMP statistics ingested by one or more Minions in order to alleviate load on the core.
```

2023-07-19 14:18 UTC, Bonrob2 commented on docs/modules/reference/pages/telemetryd/protocols/bmp/bmp.adoc
> +In this mode, events are sent back to the message broker to be processed by the core and metrics are persisted directly to the time-series database.
```suggestion
In this mode, events are sent back to the message broker for the core to process and metrics are persisted directly to the time series database.
```

2023-07-19 14:18 UTC, Bonrob2 commented on docs/modules/reference/pages/telemetryd/protocols/bmp/bmp.adoc
> +TIP: The https://github.com/OpenNMS-forge/bmp-playground[BMP Playground] provides a virtual lab that can be used to simulate BGP, BMP, and see how the OpenNMS components can be configured at runtime.
```suggestion
TIP: The https://github.com/OpenNMS-forge/bmp-playground[BMP Playground] provides a virtual lab that you can use to simulate BGP, BMP, and to see how the {page-component-title} components can be configured at runtime.
```

2023-07-19 14:40 UTC, Bonrob2 approved these changes
docs LGTM! Thanks!

2023-07-19 20:33 UTC, dino2gnt commented
LGTM.  Should this go to a `foundation` ?

2023-07-26 13:36 UTC, Bonrob2 approved these changes
LGTM!

2023-08-01 13:17 UTC, merged