NMS-16033: Update docs on default RRD
OpenNMS/opennms pull request #6459
Opened 2023-07-31 19:07 UTC by mmahacek

### All Contributors

* [X] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [X] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16033

2023-07-31 19:12 UTC, dino2gnt approved these changes
LGTM

2023-08-01 14:18 UTC, Bonrob2 requested changes
a few minor changes.

2023-08-01 14:18 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/retention.adoc
> +5 minute averages kept for 7 days.
```suggestion
5-minute averages kept for 7 days.
```

2023-08-01 14:18 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/retention.adoc
> +1 hour average kept for 62 days.
```suggestion
1-hour average kept for 62 days.
```

2023-08-01 14:18 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/retention.adoc
> +1 day average kept for 366 days.
```suggestion
1-day average kept for 366 days.
```

2023-08-01 18:14 UTC, Bonrob2 submitted a review, later dismissed
LGTM! Thanks!

2023-08-01 18:37 UTC, mmahacek commented on docs/modules/operation/pages/deep-dive/retention.adoc
> +With this "round robin" storage, data is kept in aggregated time buckets, with the latest bucket overwriting the oldest bucket, and multiple collections within the time period for a bucket will cause
```suggestion
With this "round robin" storage, data is kept in aggregated time buckets, with the latest bucket overwriting the oldest bucket.
Multiple collections within the time period for a bucket will cause the data to be consolidated based on the type of bucket.
```

2023-08-04 13:10 UTC, Bonrob2 approved these changes
LGTM!

2023-08-04 14:49 UTC, merged