NMS-16210: Structured Node List documentation
OpenNMS/opennms pull request #6849
Opened 2023-11-08 21:03 UTC by synqotik

Documentation for the Horizon 33 Structured Node List.

This is a first draft, I expect there will be edits and updates.

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16210

2023-11-09 16:21 UTC, Bonrob2 requested changes
It looks like a lot, but mainly stylistic and style guide updates. Thanks for all this work!

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +Use "Clear All" to clear all filters and search parameters.
```suggestion
Use **Clear All** to clear all filters and search parameters.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +The Categories section allows you to enable "Match All", in which case only nodes corresponding to *all* the selected categories (i.e. the "intersection") will be displayed.
```suggestion
Use **Match All** in the Categories section to display only nodes corresponding to *all* the selected categories.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Search by System Location. Performs a case-sensitive wildcard search.
```suggestion
| Performs a case-sensitive wildcard search by system location.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Search by SNMP Alias. Performs an exact search.
```suggestion
| Performs an exact search by SNMP alias.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Search by SNMP Description. Performs an exact search.
```suggestion
| Performs an exact search by SNMP description.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Search by SNMP Index. Performs an exact search.
```suggestion
| Performs an exact search by SNMP index.
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +== Node Table
```suggestion
== Node table
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +== Action Menu
```suggestion
== Action menu
```

2023-11-09 16:21 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +== Node Details
```suggestion
== Node details
```

2023-11-09 20:19 UTC, synqotik commented on docs/modules/operation/images/structured-node-list/node-details.png
Yes, fixed in screenshot and in code (both in Node Details dialog and in Extended Search dropdown).

2023-11-09 20:20 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +:description: Provides details about the Structured Node List of {page-component-title}.
Done

2023-11-09 20:22 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +The {page-component-title} 33 Web UI includes a new feature, the Structured Node List.
Done

2023-11-09 20:23 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +This is a Vue-based page which displays node information and enables the user to perform enhanced data display, searching, filtering, and data export.
Done

2023-11-09 20:24 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +Most of the columns can be sorted in ascending or descending order.
Done

2023-11-09 20:25 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +You can choose between 10, 20 or 50 entries per page, and can navigate between pages, or go to the start or end of the currently filtered set.
Done

2023-11-09 20:25 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +image::structured-node-list/node-structure-overview.png["{page-component-title} web UI showing structured node list"]
Done

2023-11-09 20:48 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +Above the table is a button that allows you to export the current data in either CSV or JSON format.
Yes, added, and also added one for the gear symbol.

2023-11-09 21:04 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Display the Node Details dialog
Changed to be a list. Also updated some of the names both in this list and in the dropdown and image.

2023-11-09 21:06 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Navigate to the Events page
Fixed all these to be a list

2023-11-09 21:20 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +Click the checkbox next to each column to display or hide that column. Note that changes take effect immediately.
It's admittedly a little tricky. Changes take effect immediately in that they are "saved" in the Vue runtime code. But if user hard-refreshed the page those changes would be lost unless they clicked "Save and Close".

There's some explanation below re the Save feature. It saves by using the web browser's "local storage" facility. So preferences are stored for that browser on that machine only. No one else will see the changes, and that user would not see them if they used a different browser even on same machine, or used a different machine.

Saving preferences by OpenNMS user would be more ideal, but more work, and seems we should coordinate a general "User Preferences" system probably using Content Management.

2023-11-09 21:43 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +NOTE: Node Preferences are stored in your browser's `Local Storage`.
Good idea, done!

2023-11-09 21:54 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +As items are selected, the number of items selected will display; a check icon will display to clear that section's selections.
This sentence specifically means the number of items selected is shown.

I updated to:

```
As items are selected, the number of items selected for that section will display.
A check symbol lets you clear the selected items for that section.
```

The image makes it a little clearer: items selected are shaded light gray, and the number appears next to the section name, e.g. "Categories (2) (x)"

2023-11-09 21:56 UTC, synqotik commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +| Search by Foreign Source only
fixed all of these

2023-11-09 22:06 UTC, synqotik commented
I believe I addressed everything :)

Note, there's a build failure which I don't think has anything to do with this PR, ticket opened: https://opennms.atlassian.net/browse/NMS-16227

2023-11-13 15:06 UTC, Bonrob2 requested changes
A few things I missed the first time through. Thanks!

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +You can filter by Category (for example, Surveillance Category), flows, and monitoring locations.
```suggestion
You can filter by category (for example, surveillance category), flows, and monitoring locations.
```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +As items are selected, the number of items selected for that section will display.
```suggestion
As you choose items, the number of items selected for that section will display.
```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +Use **Match All** in the Categories section to display only nodes corresponding to *all* the selected categories.
```suggestion
Use **Match All** in the Categories section to display only nodes corresponding to all the selected categories.
```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +This allows you to search by various additional fields.
```suggestion
This lets you to search by additional fields.
```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +The Horizon 33 Web UI includes a new feature, the Structured Node List.
```suggestion

```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +You can choose among 10, 20 or 50 entries per page, navigate between pages, or go to the start or end of the currently filtered set.
```suggestion
You can choose among 10, 20, or 50 entries per page, navigate among pages, or go to the start or end of the currently filtered set.
```

2023-11-13 15:06 UTC, Bonrob2 commented on docs/modules/operation/pages/deep-dive/structured-node-list/introduction.adoc
> +A gear icon image:structured-node-list/node-preferences-button.png[width=32] opens the Node Preferences window that allows you to configure the columns displayed and their order.
```suggestion
A *gear* symbol image:structured-node-list/node-preferences-button.png[width=32] opens the Node Preferences window that allows you to configure the columns displayed and their order.
```

2023-11-13 16:49 UTC, Bonrob2 approved these changes
Docs LGTM! Thanks!

2023-11-13 16:51 UTC, synqotik commented
> A few things I missed the first time through. Thanks!

Fixed! Also merged into `develop` to fix a merge conflict.

2023-11-13 18:34 UTC, Bonrob2 approved these changes
Looks even better now! :-)

2023-11-13 18:35 UTC, merged