NMS-16143: Allow per connection pool config and split out monitoring connection
OpenNMS/opennms pull request #7038
Opened 2024-01-24 15:52 UTC by fooker

Backport of https://github.com/OpenNMS/opennms/pull/6695

### External References

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16107

2024-01-24 15:59 UTC, RangerRick approved these changes

2024-01-24 17:27 UTC, RangerRick requested changes
Wait, are we using the _admin_ connection at runtime?  Is there a reason it should be using `${install.database.admin.*}` instead of `${install.database.*}`? That seems like a huge security issue, we shouldn't be initializing any direct database connections as the admin user at runtime, only at install.

2024-01-24 19:16 UTC, RangerRick requested changes
Oh wait, I guess this is for monitoring postgres itself? It doesn't appear that `foundation-2023` actually has any config that _uses_ that though.

Should we even be adding the `opennms-monitor` datasource in the backport? Or should we _also_ be backporting the selfmonitor support?

2024-01-25 14:36 UTC, fooker commented
> Oh wait, I guess this is for monitoring postgres itself? It doesn't appear that `foundation-2023` actually has any config that _uses_ that though.
> 
> Should we even be adding the `opennms-monitor` datasource in the backport? Or should we _also_ be backporting the selfmonitor support?

I don't think that we should backport self-monitoring at this point. Users still can build it themself, when it comes to DB monitoring.

2024-01-25 15:01 UTC, RangerRick approved these changes

2024-02-07 15:16 UTC, merged