NMS-16320: Fixed requisition handling
OpenNMS/opennms pull request #7103
Opened 2024-02-20 07:08 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/NMS-16320

2024-02-20 14:19 UTC, RangerRick requested changes
As far as I can tell the rest looks ok, just weird to log an `error` rather than `warning` but not actually throw an exception.

2024-02-20 15:08 UTC, christianpape commented on integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlConnection.java
> +        }
done.

2024-02-20 20:29 UTC, RangerRick submitted a review, later dismissed

2024-02-21 15:14 UTC, RangerRick approved these changes

2024-02-22 08:05 UTC, merged