NMS-16417: Make the refresh work again
OpenNMS/opennms pull request #7334
Opened 2024-06-19 13:52 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/NMS-16417

2024-06-25 14:00 UTC, synqotik requested changes
See comments - looks like this works, but I believe it could be updated to make the intent of the code more clear.

2024-06-26 06:58 UTC, christianpape commented
> See comments - looks like this works, but I believe it could be updated to make the intent of the code more clear.

The function was pretty versatile, but for the given case it wasn't necessary. I simplified the code.

2024-06-27 16:42 UTC, synqotik approved these changes
Looks good - just one comment, not sure if it's needed or not. If you need me to re-approve, please ping me!

Also some failing tests, but they may not be related to this PR at all.

2024-06-27 18:14 UTC, mvrueden commented on opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
> +        window.location.href = document.location.href + '?id=${alarmId}';
In my opinion best practice would be to use https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams, which could handle that automatically.

2024-06-28 14:16 UTC, synqotik approved these changes
Looks good!

2024-06-28 14:16 UTC, synqotik commented on opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
> +    let url = new URL(location.href);
Nice!!

2024-07-02 07:25 UTC, merged