NMS-16486: Extracted caches from DocumentEnricherImpl
OpenNMS/opennms pull request #7397
Opened 2024-08-28 11:00 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/NMS-16486

2024-08-28 11:26 UTC, indigo423 approved these changes
Beside the comment, nothing I can complain about :)

2024-08-28 11:26 UTC, indigo423 commented on features/telemetry/protocols/cache/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> +    <cm:property-placeholder id="cacheConfigProperties" persistent-id="org.opennms.features.telemetry.protocols.common" update-strategy="reload">
I think it makes sense to create a documentation enhancement to add all these new configuration properties to the docs and make it a requirement when we decide to merge this into an official release. It's not a blocker for the merge into NMS-16375.

2024-08-28 12:58 UTC, fooker requested changes
Main itch is the naming. The `NodeMetadataCache` gives out `NodeInfo`. Also the package naming does not reflect the maven project structure. `NodeInfo` is located in `.../protocols/common/cache` where as `protocols/common` and `protocols/cache` both exist.

2024-08-28 13:01 UTC, christianpape commented
> Main itch is the naming. The `NodeMetadataCache` gives out `NodeInfo`. Also the package naming does not reflect the maven project structure. `NodeInfo` is located in `.../protocols/common/cache` where as `protocols/common` and `protocols/cache` both exist.

Yes, you are totally right. The common.cache is a leftover of changes I reverted. I'll fix that.

2024-08-29 10:30 UTC, indigo423 approved these changes
LGTM!

2024-08-30 06:13 UTC, merged