NMS-16482: Version in about page points to invalid release notes.
OpenNMS/opennms pull request #7482
Opened 2024-10-21 11:39 UTC by Junaid-Khan-Nant

- https://opennms.atlassian.net/browse/NMS-16482

2024-10-22 16:44 UTC, smunir-onms commented on opennms-webapp/src/main/webapp/about/index.jsp
> +    <td><a href="https://docs.opennms.com/meridian/<%="2024"%>/releasenotes/whatsnew.html" target="_blank" title="Release Notes"><%=Vault.getProperty("version.display")%></a></td>
Right, to make it dynamic there should be a property like "opennms.product" and the version property shouldn't be replaced with hardcoded "value 2024"

2024-10-23 13:30 UTC, indigo423 requested changes
This change needs to be made in the private repository https://github.com/opennms/opennms-prime. @cgorantla, yes this is a good idea having a property where we can set the "distribution" at compile time would be helpful.

2024-10-23 16:49 UTC, Junaid-Khan-Nant commented
> This change needs to be made in the private repository https://github.com/opennms/opennms-prime. @cgorantla, yes this is a good idea having a property where we can set the "opennms.product" at compile time would be helpful.

@cgorantla , don't have access for this [repository.](https://github.com/opennms/opennms-prime).

2024-10-23 16:57 UTC, smunir-onms commented on opennms-webapp/src/main/webapp/about/index.jsp
> +    <td><a href="https://docs.opennms.com/<%=Vault.getProperty("opennms.product")%>/<%=Vault.getProperty("release.version")%>/releasenotes/whatsnew.html" target="_blank" title="Release Notes"><%=Vaul
Don't add a new property "release.version", use "version.display" instead, docs page path and properties values would be adjusted accordingly. @cgorantla @indigo423 please correct me if am wrong. 
```suggestion 
    <td><a href="https://docs.opennms.com/<%=Vault.getProperty("opennms.product")%>/<%=Vault.getProperty("release.version")%>/releasenotes/whatsnew.html" target="_blank" title="Release Notes"><%=Vault.getProperty("opennms.product")%> - <%=Vault.getProperty("version.display")%></a></td>
```

2024-10-23 21:35 UTC, indigo423 requested changes
We should think about a way to control these settings at build time with maven. It allows us to set it in the build jobs for Meridian / Horizon rather than hard coding it in properties.

2024-10-23 21:35 UTC, indigo423 commented on opennms-webapp/src/main/web-filtered/WEB-INF/version.properties
> +version.display=2024.1.3
We should not hardcode the version here. The `${display.version}` is set from the pom.xml using `${install.version}` and follows automatically the correct version number. Hardcoding the version number would require dealing with it manually.

2024-10-23 21:35 UTC, indigo423 commented on opennms-webapp/src/main/webapp/about/index.jsp
> +    <td><a href="https://docs.opennms.com/<%=Vault.getProperty("opennms.product")%>/<%=Vault.getProperty("version.display")%>/releasenotes/whatsnew.html" target="_blank" title="Release Notes"><%=Vaul
What about doing a similar thing, setting a property in the pom.xml like `${install.product}` which is evaluated from a single place from the pom.xml which we can control at build time with maven?

2024-10-25 11:17 UTC, Junaid-Khan-Nant commented
Hi @indigo423,  the property related to product name has been added and tested, and it's working fine. I am facing issues on the version as it is also used in inner pom's xml. If I replace this 33.0.3-SNAPSHOT with 2024.1.3-SNAPSHOT, then initial is working fine, but after a few times it stops the server with the following logs.
![log-2](https://github.com/user-attachments/assets/0d28cb78-6721-4be9-9dc9-deda0b246a75)
![log-1](https://github.com/user-attachments/assets/bd0b96fa-2132-4f24-a35f-8a0b359dd2fa)
Any idea about it? Or I believe there is another way to create a new tag just like we created for the product and mention the release version there.It would be in parent pom.xml.Your opinion?

2024-10-29 13:42 UTC, mershad-manesh commented on pom.xml
> +    <install.product>meridian</install.product>
This should be `horizon` as `Foundation-` branches are based on `horizon`.

2024-10-29 16:59 UTC, cgorantla reviewed
Also you can update this in following pages

````
git grep "docs.opennms.com"
src/main/webapp/about/index.jsp:73:    <td><a href="https://docs.opennms.com/horizon/<%=Vault.getProperty("version.display")%>/releasenotes/whatsnew.html" target="_blank" title="Release Notes"><%=Vault.getProperty("version.display")%></a></td>
src/main/webapp/includes/help-documentation.jsp:63:                            href="https://docs.opennms.com/horizon/<%=Vault.getProperty("version.display")%>/deployment/core/introduction.html"
src/main/webapp/includes/help-documentation.jsp:70:                            href="https://docs.opennms.com/horizon/<%=Vault.getProperty("version.display")%>/operation/overview/overview.html#overview"
src/main/webapp/includes/help-documentation.jsp:77:                            href="https://docs.opennms.com/horizon/<%=Vault.getProperty("version.display")%>/development/overview/overview.html#overview"
```

2024-10-29 16:59 UTC, cgorantla commented on pom.xml
> +    <product.name>${install.product}</product.name>
```suggestion
    <product.name>meridian</product.name>
```

2024-10-29 16:59 UTC, cgorantla commented on pom.xml
> +    <install.product>meridian</install.product>
```suggestion
```

2024-10-29 16:59 UTC, cgorantla commented on pom.xml
> +    <product.name>${install.product}</product.name>
Add another property as
<docs.product.version>24</docs.product.version>

2024-11-05 15:37 UTC, cgorantla commented on pom.xml
> +    <docs.product.version>2024</docs.product.version>
```suggestion
    <docs.product.version>33</docs.product.version>
```

2024-11-06 17:49 UTC, cgorantla approved these changes
LGTM!

2024-11-06 17:50 UTC, merged