NMS : 15717 : DeviceConfig via Minion fails if sshScript output contains control characters.
OpenNMS/opennms pull request #7537
Opened 2024-11-19 13:09 UTC by Junaid-Khan-Nant

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15717

2024-11-29 15:01 UTC, Junaid-Khan-Nant commented
Hi @cgorantla , I have tried it with Juniper. Please see the results in screenshots. 

![2](https://github.com/user-attachments/assets/16e1fa2b-7411-421a-9211-6bf4a197dcc7)
![1](https://github.com/user-attachments/assets/686daa63-18ab-461a-8783-749b0d44d55e)

Also tried with dcb-trigger using karaf and minion facing below errors: 

![Screenshot from 2024-11-29 19-31-11](https://github.com/user-attachments/assets/db2b5bc8-f0b4-4b80-9d2e-c1836753ee3d)

2024-12-18 11:47 UTC, Junaid-Khan-Nant commented
Hi @cgorantla , please see the screenshots.
![image (2)](https://github.com/user-attachments/assets/93e22ca6-6654-4f03-b37f-316714fdf52c)
![image (1)](https://github.com/user-attachments/assets/85e67c4e-3703-46cb-9204-3c4999a93b67)

2024-12-24 09:17 UTC, Mohammad-Junid reviewed
Seems fine to me

2025-01-13 19:45 UTC, cgorantla reviewed
@Junaid-Khan-Nant  Did you try with latest versions of eclipse persistence ? Can you have a branch that shows upgraded versions still fail these tests ? 
 I would prefer to avoid customizations for these core things.

2025-01-15 09:28 UTC, christianpape requested changes

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/main/java/org/opennms/netmgt/poller/EscapeSequenceAdapter.java
> + * Copyright (C) 2023 The OpenNMS Group, Inc.
This must be 2025

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/main/java/org/opennms/netmgt/poller/EscapeSequenceAdapter.java
> + * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
1999-2025

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/main/java/org/opennms/netmgt/poller/EscapeSequenceAdapter.java
> +        try {
why try-catch here?

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/main/java/org/opennms/netmgt/poller/EscapeSequenceAdapter.java
> +        try {
why try-catch here?

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/test/java/org/opennms/netmgt/poller/DeviceConfigTest.java
> + * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
2025

2025-01-15 09:28 UTC, christianpape commented on features/poller/api/src/test/java/org/opennms/netmgt/poller/EscapeSequenceAdapterTest.java
> + * OpenNMS(R) is Copyright (C) 1999-2023 The OpenNMS Group, Inc.
2025

2025-01-15 12:01 UTC, christianpape approved these changes

2025-01-15 14:40 UTC, cgorantla approved these changes
lgtm!

2025-01-15 14:43 UTC, merged