NMS-16943 : De-Sync Bug between Web UI and SCVCLI Command.
OpenNMS/opennms pull request #7554
Opened 2024-12-05 10:26 UTC by Junaid-Khan-Nant

- https://opennms.atlassian.net/browse/NMS-16943

2024-12-05 10:38 UTC, Junaid-Khan-Nant commented
![Screenshot from 2024-12-04 22-45-32](https://github.com/user-attachments/assets/2e97f208-aa8d-4d97-a77e-fffdb4af3150)
![Screenshot from 2024-12-04 22-45-24](https://github.com/user-attachments/assets/f98273e6-66fa-4912-80ef-46dadb1998f9)
![Screenshot from 2024-12-04 22-45-16](https://github.com/user-attachments/assets/b7e0f237-bcae-49f8-9287-e68cbff4aa74)

2024-12-06 21:50 UTC, cgorantla reviewed
Don't think these changes are solving the problem properly.

Looks like this problem occurs because cache is invalid when we add credentials form scvcli.

Two ways to solve this issue:

1. We may have to watch for file updates with `FileReloadContainer` and reload the cache  when the keystore file gets updated. 

2. Add a button to reload cache in UI and implement in Rest api and service.

I would prefer to try with 1  option.

2024-12-06 22:02 UTC, cgorantla commented
Or may be try using `FileUpdateWatcher` to reload the cache.

2024-12-06 23:05 UTC, cgorantla requested changes
proposed couple of solutions to solve this properly.

2024-12-09 10:16 UTC, aurang-zeb313 commented on features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
> +                m_credentialsCache.put(aliass, fromBase64EncodedByteArray(new String(keySpec.getPassword()).getBytes()));
synchronize the block

2025-01-08 15:44 UTC, cgorantla commented
Should be handled by https://github.com/OpenNMS/opennms/pull/7566

2025-01-08 15:44 UTC, closed without merging